### ISSUE TITLE
Support JetBrains Aqua IDE as `type`

### ISSUE THREAD

**Issue by YannCebron** [JetBrains/intellij-platform-gradle-plugin#1191]
**Is your feature request related to a problem? Please describe.**
Support Aqua IDE (https://www.jetbrains.com/aqua/) "natively" as new `type` in configuration.

**Additional context**
- once it gets to Beta or similar
- MP-4901

**Comment by hsz** [comment]
Added to the `IntelliJPlatformType` as a binary dependencies as there are no IntelliJ Platform Maven repository coordinates available.
