### ISSUE TITLE
[Plugin Verifier] Download URL should be adjustable

### ISSUE THREAD

**Issue by DreierF** [JetBrains/intellij-platform-gradle-plugin#1232]
**Is your feature request related to a problem? Please describe.**
We face a huge amount of external traffic in our CI due to running the plugin verifier. What we would like to be able to do is to cache the IDE downloads in a local proxy (Nexus) how it already happens for the [jbr](https://cache-redirector.jetbrains.com/intellij-jbr), [plugins](https://cache-redirector.jetbrains.com/plugins.jetbrains.com/maven) and [releases](https://www.jetbrains.com/intellij-repository/releases) repositories.

Currently the URLs seems to be hardcoded [here](https://github.com/JetBrains/gradle-intellij-plugin/blob/0f38f3ed8fb5eab0f76ac47b1c24e22638a7de9b/src/main/kotlin/org/jetbrains/intellij/tasks/RunPluginVerifierTask.kt#L477). I also don't quite understand why the [releases](https://www.jetbrains.com/intellij-repository/releases) repository is not reused here.

**Describe the solution you'd like**
I would like to have the possibility to override the location and ideally have it use a maven layout based URL that can be proxied.

**Describe alternatives you've considered**
Only running the plugin verifier in nightly builds or weekend builds.

**Comment by YannCebron** [comment]
as a workaround, you can provide artifacts manually and set `localPaths` https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#tasks-runpluginverifier-localpaths instead of relying on the automatic provision by Plugin Verifier task

**Comment by YannCebron** [comment]
related #1142

**Comment by hsz** [comment]
@DreierF 

> Currently the URLs seems to be hardcoded [here](https://github.com/JetBrains/gradle-intellij-plugin/blob/0f38f3ed8fb5eab0f76ac47b1c24e22638a7de9b/src/main/kotlin/org/jetbrains/intellij/tasks/RunPluginVerifierTask.kt#L477). I also don't quite understand why the [releases](https://www.jetbrains.com/intellij-repository/releases) repository is not reused here.

Plugin Verifier uses actual IDEs distributions — the ones you download for further use on your machine.
In addition, the Maven releases repository we use for building plugins doesn't contain sources of every IDE you may want to run verification against.

**Comment by hsz** [comment]
IDEs for IntelliJ Plugin Verifier are now handled through Gradle dependencies with a dedicated extension exposed, see: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-extension.html#intellijPlatform-verifyPlugin-ides

The download URL, or rather a repository from which IDEs are downloaded, is defined with the `binaryReleases()` repository helper: https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/81dbc0216098201e14032418899cc2ff79dd3cbf/src/main/kotlin/org/jetbrains/intellij/platform/gradle/extensions/IntelliJPlatformRepositoriesExtension.kt#L142-L165

To use it, simply add:

```
repositories {
  intellijPlatform {
    ...
    binaryReleases()
  }
}
```

Given that, we use repositories for selecting files, it is easily possible to introduce custom locations, if needed.
