### ISSUE TITLE
RunIde tasks doesn't work on repo from template

### ISSUE THREAD

**Issue by MarcinAman** [JetBrains/intellij-platform-gradle-plugin#1273]
**Describe the bug**
Out of the box `runIde` task fails because it relies on `patchPluginXml` which doesn't work

**To Reproduce**
1) Create template from: https://github.com/JetBrains/intellij-platform-plugin-template
2) invoke `runIde`

Repository: https://github.com/MarcinAman/changelog-bug
Job: https://github.com/MarcinAman/changelog-bug/actions/runs/3837109214/jobs/6532043011#step:5:63
(ok, invoking `runIde` on GH actions is quite dumb but if fails before the task is run :D )

**Expected behavior**
It works

**Environment:**
N/A

**Additional context**
Workaround is to comment out changelog part: https://github.com/MarcinAman/changelog-bug/blob/435b3fa0822a51e275466ed0195b2edcabe0477f/build.gradle.kts#L87

**Comment by hsz** [comment]
Cannot recreate that with the latest versions of the tools.
