### ISSUE TITLE
Deterministic order of ideaIC dependencies

### ISSUE THREAD

**Issue by rubenpieters** [JetBrains/intellij-platform-gradle-plugin#1284]
**Is your feature request related to a problem? Please describe.**
The plugin seems to have a non-deterministic order when it's utilizing the ideaIC dependencies. When I compare a gradle build scan for a build on different machines, I can see that the ordering of the dependencies in the classpath is different:

![Screenshot from 2023-01-20 13-48-11](https://user-images.githubusercontent.com/2465652/213699011-9c8b91f4-bb2e-41a6-9973-c9c61e12540e.png)

**Describe the solution you'd like**
Ideally these dependencies would have a [deterministic order](https://docs.gradle.org/current/userguide/dependency_management.html#sub:file_dependencies), this way gradle can use the cache when the sources haven't changed. It looks like it could be related to the use of `FileTree` in `DependenciesUtils` ([link](https://github.com/JetBrains/gradle-intellij-plugin/blob/26bde9b1c6830de4aafab8e334deac74b7a98289/src/main/kotlin/org/jetbrains/intellij/DependenciesUtils.kt)). Maybe the dependencies could be sorted?

**Additional context**
Relevant gradle snippet:

```
plugins {
    ..
    id 'org.jetbrains.intellij' version '1.12.0'
    ..
}

intellij {
    setVersion('IC-2018.3.4')
    setPlugins(['android'])
    setPluginName('...')
    downloadSources.set(true)
}
```

**Comment by hsz** [comment]
There's a plan to rework dependencies management so everything that is required for building the plugin will be explicitly described in the `dependencies {}` closure of the build script.

**Comment by hsz** [comment]
Starting with the IntelliJ Platform Gradle Plugin, all dependencies — including the IntelliJ Platform — are defined within the `dependencies {}` block, which makes it possible to control the order.
Please see: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-dependencies-extension.html
