### ISSUE TITLE
UnknownHostException: cache-redirector.jetbrains.com when working offline

### ISSUE THREAD

**Issue by ahus1** [JetBrains/intellij-platform-gradle-plugin#1342]
**Describe the bug**

I tried to open my plugin project in IntelliJ while I was offline. IntelliJ wanted to run Gradle to update the model. As I was offline, this failed.

**To Reproduce**

Possible reproducer: Wait for a day or two until all SNAPSHOTs are considered old.  Then try to use a plugin project offline. See exception below.

The plugin I used: https://github.com/asciidoctor/asciidoctor-intellij-plugin

**Expected behavior**

As the dependencies were downloaded the day before, it should have just worked.

**Environment:**

```
$ ./gradlew --version

------------------------------------------------------------
Gradle 7.6
------------------------------------------------------------

Build time:   2022-11-25 13:35:10 UTC
Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.3 (Amazon.com Inc. 17.0.3+6-LTS)
OS:           Windows 11 10.0 amd64

```

**Additional context**

Console output: 
[console.log](https://github.com/JetBrains/gradle-intellij-plugin/files/10934764/console.log)

**Comment by YannCebron** [comment]
Did you switch IntelliJ Gradle support to Offline modus?

**Comment by ahus1** [comment]
Adding to my previous comment: I would expect that it would reuse an old snapshot it it can't download a new snapshot. Please comment/close if this shouldn't be the case.

**Comment by hsz** [comment]
With the `2.0` release, all dependencies are fully managed with by Gradle. If anything will fail, it's them, not us. :)
