### ISSUE TITLE
Must not use `executable` property on `Test` together with `javaLauncher` property

### ISSUE THREAD

**Issue by jansorg** [JetBrains/intellij-platform-gradle-plugin#1358]
**Describe the bug**
I updated from 1.13.2 to 1.13.3. With the new version, the following error is shown for a `./gradlew clean build`, but I don't have defined any of these properties.

```
> Task :core-shared:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core-shared:test'.
> Must not use `executable` property on `Test` together with `javaLauncher` property
```

**To Reproduce**
Sorry, this isn't a public repository.

**Expected behavior**

**Environment:**
 - OS: Linux
 - Gradle IntelliJ Plugin Version 1.13.2
 - Gradle Version: Gradle Wrapper 7.5.1

**Comment by hsz** [comment]
Seems it's an issue with Gradle 7.x. Are you able to switch to 8.x?

**Comment by MCMicS** [comment]
same to me for Gradle 7.
After Upgrade to Gradle 8 the erro ris gone

Build Error; https://github.com/MCMicS/jenkins-control-plugin/actions/runs/4589330799

**Comment by duemir** [comment]
Ditto, Gradle 7.5.1.
https://github.com/jenkinsci/idea-stapler-plugin/pull/148/checks?check_run_id=12414944325
Upgrading to Gradle 8 noted

**Comment by jansorg** [comment]
Unfortunately I can't switch to Gradle 8.x for some of my projects because there's at least one other Gradle plugin incompatible with 8.x.

**Comment by hsz** [comment]
JBR is now in `2.0` registered from the scratch using the `IntelliJPlatformJavaLauncher` class — Gradle respects that in the same way as already provided Java Runtimes.
