### ISSUE TITLE
Support authenticated plugin repositories in plugin dependencies

### ISSUE THREAD

**Issue by MarcinAman** [JetBrains/intellij-platform-gradle-plugin#1372]
**Is your feature request related to a problem? Please describe.**
Right now it is impossible to depend on a plugin that is available behind authorised plugin repository

**Describe the solution you'd like**
Option to add authorisation header that would be copied to requests "as-is" without any changes.

**Describe alternatives you've considered**
Right now you are able to depend on a plugin that is pre-downloaded on disk but it is annoying

**Comment by hsz** [comment]
IntelliJ Platform Gradle Plugin 2.0 uses Gradle repositories, which can be customized. It's possible to involve all auth options described in Gradle docs: https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:authentication_schemes
