### ISSUE TITLE
Adds a `testPlugins`

### ISSUE THREAD

**Issue by bric3** [JetBrains/intellij-platform-gradle-plugin#1387]
**Is your feature request related to a problem? Please describe.**
Often during development, the tests requires some plugin to make the test runnable. 
I would like to limit the actual dependencies (as in compile time dependencies). So I would like to be able to express these runtime dependencies in different scope.

**Describe the solution you'd like**

At this time the plugins are declared in the `intellij` extension, so this would like : 

```kotlin
intellij {
   // ...

   plugins.set(
       "org.intellij.plugins.markdown",
   )
   testPlugins.set(
       "org.intellij.plugins.markdown",
       "com.intellij.java",
   )
}
```

Note the `testPlugins` in this proposition do not inherit the `plugins` list, so that custom configurations could be used with or without plugins. That said I wonder if this is the right approach.

**Describe alternatives you've considered**

At this time, the code has to declare plugins in the compile scope even if those are only used for tests, e.g.:

```kotlin
intellij {
    type.set("IC")
    plugins.set(
        listOf(
            "Git4Idea",
            "com.intellij.java" // for tests
            "org.intellij.plugins.markdown",
        )
    )
}
```

**Additional context**
Somewhat related but out of scope, I believe plugins should be declared as dependencies with their configurations in order to rely on the Gradle semantics, e.g.

```kotlin
dependencies {
    // regular dependencies
    implementation(...)
    testImplementation(...)

    // plugins
    plugin(...)
    testPlugin(...)
}
```

**Comment by YannCebron** [comment]
related #336, #115

**Comment by hsz** [comment]
Starting with `2.0` release, it is now possible to register new test/run tasks with customized IntelliJ Platform and plugins set:

```
val customRunIde by intellijPlatformTesting.runIde.registering {
    type = IntelliJPlatformType.Rider
    version = "2024.2"

    plugins {
        plugin("pluginId:version")
        plugin(pluginId, version, channel)
        disablePlugins(bundledPlugiId)
    }
}

val customTest by intellijPlatformTesting.testIde.registering {
    ...
}
```
