### ISSUE TITLE
verifyPlugin fails due to multiple plugin descriptors

### ISSUE THREAD

**Issue by SingingBush** [JetBrains/intellij-platform-gradle-plugin#1412]
[intellij-dlanguage](https://github.com/intellij-dlanguage/intellij-dlanguage) is stuck using gradle-intellij-plugin 1.10.1 because newer versions (1.13.3 and 1.14.1) fail to run `:verifyPlugin` with our project:

```
[gradle-intellij-plugin :verifyPlugin] Found multiple plugin descriptors 'plugin.xml' from 'DLanguage-1.30.2-SNAPSHOT.jar' and 'plugin.xml' from 'instrumented-DLanguage-1.30.2-SNAPSHOT.jar'

Execution failed for task ':verifyPlugin'.
> Plugin verification failed.
```

**To Reproduce**
clone the repo and bump plugin to 1.14.1 then run verifyPlugin with the gradle wrapper

**Comment by YannCebron** [comment]
please make sure to adapt your plugin according to this https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#multi-module-project

**Comment by SingingBush** [comment]
I've tried to update my project dependencies using the _instrumentedJar_ but as one of the modules depends on the plugin code of the main code it errors due to circular dependencies. This has always been ok before though.

```
Circular dependency between the following tasks:
:classes
\--- :compileJava
     +--- :compileKotlin
     |    \--- :instrumentedJar
     |         +--- :classes (*)
     |         +--- :compileJava (*)
     |         +--- :compileKotlin (*)
     |         \--- :instrumentCode
     |              \--- :classes (*)
     \--- :instrumentedJar (*)
```

**Comment by SingingBush** [comment]
I changed the dependencies section of the sub project that requires the main source to use _compileOnly_ and it seems to be working fine

https://github.com/intellij-dlanguage/intellij-dlanguage/commit/e6f849a05e071d3810b64fa3a7b37ba0091e32ff

```
dependencies {
    compileOnly project(':')
    compileOnly project(':utils')
    compileOnly project(':errorreporting')
}
```

**Comment by hsz** [comment]
Obsolete, as fixed in https://github.com/intellij-dlanguage/intellij-dlanguage/issues/885
