### ISSUE TITLE
Outdated integration test docs

### ISSUE THREAD

**Issue by TWiStErRob** [JetBrains/intellij-platform-gradle-plugin#1414]
**Describe the bug**
`CONTRIBUTING.md` contains a reference to a non-existent file in the repo and 2 links which are 404.

**To Reproduce**
Open https://github.com/JetBrains/gradle-intellij-plugin/blob/master/CONTRIBUTING.md#run-integration-tests

**Expected behavior**
CONTRIBUTING.md contains actionable information.

**Environment:**
Browser.

**Additional context**
I found https://github.com/JetBrains/gradle-intellij-plugin/blob/master/INTEGRATION_TESTS.md which contains references to `verify.main.kts`, but unclear where that file comes from.

I also found https://github.com/JetBrains/gradle-intellij-plugin/commit/f502d8c2ed7d5b42b6b34d88f7959dc5131fcc3b, which removed/moved related files, but doesn't show the replacement.

**Comment by hsz** [comment]
Updated!
