### ISSUE TITLE
Cannot create plugin for PyCharm 2023.2 in Windows.

### ISSUE THREAD

**Issue by tonybaloney** [JetBrains/intellij-platform-gradle-plugin#1441]
I'm updating my plugin to support the latest 2023.2 release of PyCharm Pro and Community, but the test matrix is failing on Windows in 2 places:

https://github.com/tonybaloney/pycharm-security/actions/runs/5710247479/job/15470132874?pr=461

1. The Gradle extension cannot create plugin because of an XML error in the PyCharm community META-INF resource (see below)
2. The test framework is failing to load due to a missing class (probably caused by issue 1)

```
SimpleTest > testNothing() FAILED
    com.intellij.testFramework.TestLoggerFactory$TestLoggerAssertionError at TestLoggerFactory.java:403
        Caused by: java.lang.Throwable at Logger.java:370

DjangoAddMiddlewareFixerTest > initializationError FAILED
    java.lang.NoClassDefFoundError at DaemonListeners.java:343
        Caused by: java.lang.ExceptionInInitializerError at TestLoggerFactory.java:403
```

**Environment:**
 - OS: Windows
 - Gradle IntelliJ Plugin Version 1.15.0
 - Gradle Version 7.6

**Additional context**

```default
[gradle-intellij-plugin :] Cannot create plugin from file 'C:\Users\runneradmin\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.pycharm\pycharmPC\2023.2\eb057c399794f964ae5ec9facf85310b290db6ad\pycharmPC-2023.2\plugins\pycharm-community-customization': Invalid plugin descriptor 'plugin.xml': failed to resolve <xi:include>. Not found document '/META-INF/tips-pycharm-community.xml' referenced in <xi:include href="/META-INF/tips-pycharm-community.xml"/>. <xi:fallback> element is not provided. (at plugin.xml)
```

**Comment by tonybaloney** [comment]
I should also add that it compiles, tests and runs on macOS and Linux. Also all 3 platforms work against 2023.1.2

**Comment by YannCebron** [comment]
please change `yaml` to `org.jetbrains.plugins.yaml` (the plugin ID) here https://github.com/tonybaloney/pycharm-security/blob/master/build.gradle#L52

**Comment by YannCebron** [comment]
`DaemonListeners` problem is also mentioned in #1433

**Comment by tonybaloney** [comment]
Adding headless to Gradle fixed it 👍🏻 https://github.com/tonybaloney/pycharm-security/pull/461/commits/3be1f72398167da631e0cc12d441589a491743b6
