### ISSUE TITLE
`InstrumentCode` always resolves java-compiler-ant-tasks

### ISSUE THREAD

**Issue by pbreault** [JetBrains/intellij-platform-gradle-plugin#1448]
### What happened?

If the compiler version is not specified, the plugin tries to resolve it every time we run `./gradlew instrumentCode`.

Resolving the ant task version  forces a few network calls even if the task is up-to-date: 
```
> Task :instrumentCode UP-TO-DATE
[gradle-intellij-plugin :instrumentCode] Resolved non-EAP java-compiler-ant-tasks version: 231.9225.16
```

### Steps to reproduce

Using the `build.gradle.kts` below:
```kotlin
import org.jetbrains.intellij.tasks.InstrumentCodeTask

plugins {
    id("org.jetbrains.intellij") version "1.15.0"
}

group = "com.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

intellij {
    type.set("AI")
    version.set("2023.1.1.16")
}

tasks.withType<InstrumentCodeTask> {
    // Uncomment this to enable caching
    // compilerVersion.set("231.9225.16")
}
```

1. Run `./gradlew buildPlugin`
2. Run `./gradlew buildPlugin` a second time. You should see that `instrumentCode` doesn't return instantly even though it's up to date.
3. Uncomment this line: ` // compilerVersion.set("231.9225.16")`
4. Run `./gradlew buildPlugin`
5. Run `./gradlew buildPlugin` again. Should return almost instantly ( no network call )

### Gradle IntelliJ Plugin version

1.15

### Gradle version

8.1.1

### Operating System

macOS

**Comment by hsz** [comment]
With the IntelliJ Platform Gradle Plugin 2.0, the Java Compiler dependency is moved straight into the project `dependencies {}` block, so it should be resolved along with all other dependencies and not requested in the instrumentation task runtime.
