### ISSUE TITLE
Specify installed plugins for runIde task

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/intellij-platform-gradle-plugin#1489]
### Describe the need of your request

When I use runIde to test my plugin, I often need PsiViewer to validate my psi tree or to check the implemented ElementPattern in my IntelliJ plugin, like `CompletionContributor.extend`. At the moment I have to run `runIde`, wait for the IDE, go to plugins, and install the PsiViewer by myself.

### Proposed solution

Add a Gradle property that downloads specified plugins and installs the plugins automatically.

**Comment by meiMingle** [comment]
Trust me, this is a feature that already exists.
https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin-faq.html#how-to-add-a-dependency-on-a-plugin-available-in-the-file-system
https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#intellij-extension-plugins

**Comment by hfhbd** [comment]
I only want to specify preinstalled plugins for development, so the runIde task. I don' t want to depend on other plugins in production.

**Comment by hsz** [comment]
Since IntelliJ Platform Gradle Plugin `2.0.0`, it's possible to define custom test tasks and disable bundled plugins:

```
val customRunIde by intellijPlatformTesting.runIde.registering {
    type = IntelliJPlatformType.Rider
    version = "2024.2"

    plugins {
        plugin("pluginId:version")
        plugin(pluginId, version, channel)
        disablePlugins(bundledPlugiId)
    }
}

val customTest by intellijPlatformTesting.testIde.registering {
    ...
}
```
