### ISSUE TITLE
Allow wildcards and ranges in the `runPluginVerifier` > `ideVersions` list

### ISSUE THREAD

**Issue by philCryoport** [JetBrains/intellij-platform-gradle-plugin#1510]
### Describe the need of your request

Unless there's something I haven't figured out by RTFMing [the instructions](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#tasks-runpluginverifier-ideversions), we need to list 
```
{
"each",
"and",
"every",
"specific",
"IDE",
"version",
"we",
"want",
"the",
"runPluginIdentifier",
"to",
"check"
}
```

In the case of the jasyncapi AsyncAPI Preview plugin, our under-review version has the following code block:
```
tasks.getByName<org.jetbrains.intellij.tasks.RunPluginVerifierTask>("runPluginVerifier") {
    ideVersions.set(listOf(
        "2022.3",
        "2022.3.1",
        "2022.3.2",
        "2022.3.3",
        "2023.1",
        "2023.1.1",
        "2023.1.2",
        "2023.1.3",
        "2023.1.4",
        "2023.1.5",
        "2023.2",
        "2023.2.1",
        "2023.2.2",
        "2023.2.3",
        "2023.2.4",
        "2023.2.5",
        "2023.3",
        "2023.3.1",
        "2023.3.2"
}
```

It would be nice instead to use ranges.

### Proposed solution

It would be nice instead to use ranges.  For instance, if we want to verify GA IDE versions ranging from the first 2022 version through the latest 2023 version, inclusive, it would be great if we could just write something along the lines of:
```
{
"rangeStart" : "2022.*",
"rangeEnd" : "2023.*",
"releaseType" : "GA"
}
```

...or:
{
"GA2022.*",
"GA2023.*",
}

### Alternatives you've considered

As mentioned above, RTFM'd and didn't see how to use wildcards or ranges.

### Additional context

N/A

**Comment by YannCebron** [comment]
If no specific IDEs/versions are listed, it will verify against given `since/until-build` by default. Does that match your use case?

**Comment by philCryoport** [comment]
> If no specific IDEs/versions are listed, it will verify against given `since/until-build` by default. Does that match your use case?

Thanks!  I'll let the other members know...

**Comment by philCryoport** [comment]
@YannCebron `sinceBuild` and `since` not working for my config file's `runPluginVerifier` section:

Code change:

![image](https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/28901899/27571bdc-ea37-46fb-a4b3-3d673eaf68f4)

I removed the list of specific versions in `runPluginVerifier` -- and instead tried:

`ideVersions.set(sinceBuild("2022.3")`

Threw an error: 

```
2: Task failed with an exception.
-----------
* Where:
Build file '/Users/pschlesinger/GitHub/asyncapi/jasyncapi-idea-plugin/build.gradle.kts' line: 100

* What went wrong:
Script compilation error:

  Line 100:     ideVersions.set(sinceBuild("2022.3"))
                                ^ Unresolved reference: sinceBuild
```

The stacktrace only lists `org.gradle.*` -- nothing references `jetbrains` or `intellij`.

I also tried `ideVersions.set(since("2022.3")` and `ideVersions.set(since("IU-223")`

Same error.

[Tried to RTFM to find the syntax](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#tasks-runpluginverifier).  It wants a list:
![image](https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/28901899/3356fae3-2975-4511-8f20-1face44f89ab)

The [options link](https://github.com/JetBrains/intellij-plugin-verifier#common-options) states:

![image](https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/28901899/ab8a9295-85cc-4dee-a89c-77ae36aaf2d1)

I dug into the Github repo, searching for `ideVersions`.  [Here too it is expecting a list](https://github.com/JetBrains/intellij-plugin-verifier/blob/a0d859a5ff976e3f2f639909fa0ac43c4ecbdae9/intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/PluginsParsing.kt#L56).

What is the correct syntax to specify for the `runPluginVerifier` that it verify the plugin-under-development against IntellJ releases from `2022.3` onward?

**Comment by philCryoport** [comment]
Hi @hsz  and @YannCebron ,

Hope this follow-up is ok.  When you get a moment, would you please take a look at and respond to [my comment-reply above](https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1510#issuecomment-2070850949)?  Thanks!

**Comment by novotnyr** [comment]
Hi,
when running the Plugin Verifier, `since-build` and `until-build` are taken from your plugin descriptor. There is no need to specify that in the Gradle task explicitly again.

When your plugin has `since-build` value of `223`, it indicates compatibility with 2022.3 and later. This will be used by the Plugin Verifier, too. See [Build Number Ranges](https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#build-number-format) in the _IntelliJ Platform Plugin SDK
_.

**Comment by philCryoport** [comment]
> Hi, when running the Plugin Verifier, `since-build` and `until-build` are taken from your plugin descriptor. There is no need to specify that in the Gradle task explicitly again.
> 
> When your plugin has `since-build` value of `223`, it indicates compatibility with 2022.3 and later. This will be used by the Plugin Verifier, too. See [Build Number Ranges](https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#build-number-format) in the _IntelliJ Platform Plugin SDK_.

Hi @novotnyr 

Somehow `sinceBuild()` and `untilBuild()` are not being fully used for `runPluginVerifier` in our `build.gradle.kts` file.

Let's start with what we have now: a laundry list of every `ideVersion` we'd like to have `runPluginVerifier` to verify:
```
tasks.getByName<org.jetbrains.intellij.tasks.PatchPluginXmlTask>("patchPluginXml") {
    sinceBuild.set("223")
    untilBuild.set("241.*")
}

tasks.getByName<org.jetbrains.intellij.tasks.RunPluginVerifierTask>("runPluginVerifier") {
	verifierVersion.set("1.365")
    ideVersions.set(listOf(
        "2022.3",
        "2022.3.1",
        "2022.3.2",
        "2022.3.3",
        "2023.1",
        "2023.1.1",
        "2023.1.2",
        "2023.1.3",
        "2023.1.4",
        "2023.1.5",
        "2023.2",
        "2023.2.1",
        "2023.2.2",
        "2023.2.3",
        "2023.2.4",
        "2023.2.5",
        "2023.3",
        "2023.3.1",
        "2023.3.2",
        "2023.3.3",
        "2023.3.4",
        "2023.3.5",
        "2023.3.6",
        "2024.1"
    ))
}
```

I captured the output of `./gradlew :runPluginVerifier`:
[with_entire_listOf_ideVersions.log](https://github.com/JetBrains/intellij-platform-gradle-plugin/files/15299468/with_entire_listOf_ideVersions.log)

Here, if I want an IDE version `runPluginVerifier` verified, I have to specify it.  Kinda dumb that I need to manually curate that.  I should be able to just specify a range of versions, right?

If I read your above statement correctly, I should able to just rely on:
```
tasks.getByName<org.jetbrains.intellij.tasks.PatchPluginXmlTask>("patchPluginXml") {
    sinceBuild.set("223")
    untilBuild.set("241.*")
}
```

...and I should be able to remove the `ideVersions.set(listOf(...))`, CORRECT?

So I did that.  I commented out the entire `ideVersions.set(listOf(...))` statement.  Result from `./gradlew :runPluginVerifier`:
[removed_entire_listOf_ideVersions.log](https://github.com/JetBrains/intellij-platform-gradle-plugin/files/15299488/removed_entire_listOf_ideVersions.log)

DIFFERENCE: a ton of verifications that DID NOT OCCUR. 

FULL DIFF:
[compare_withListOfIdeVersions_versus_noListOfIdeVersions.txt](https://github.com/JetBrains/intellij-platform-gradle-plugin/files/15299503/compare_withListOfIdeVersions_versus_noListOfIdeVersions.txt)

To my eyes, `sinceBuild()` and `untilBuild()` are NOT being interpreted correctly. 

I'm hoping that maybe I'm missing something...

HELP?

**Comment by abrooksv** [comment]
At least in 2.0, that does not work @novotnyr 

```
<idea-plugin xmlns:xi="http://www.w3.org/2001/XInclude">
  <version>1.4.3</version>
  <idea-version since-build="232" />
```

yields the following:

```
[org.jetbrains.intellij.platform] Filtering releases with since='232.8660', until='232.99999', types='IC', channels='EAP,MILESTONE,BETA,RELEASE,CANARY,PATCH,RC,PREVIEW'
```

The until build isn't going up to max like it does on the marketplace

**Comment by philCryoport** [comment]
@abrooksv wrote:
> At least in 2.0, that does not work 

Apologies, I'm holding off on gradle-intelli-plugin v2.0 until it goes production...

**Comment by novotnyr** [comment]
Let's focus on the 1.x now.

Plugin Verifier is behaving correctly. However, when you leave out the `since-build` and `until-build`, you'll get the verification against most recent builds in each Platform version.

E. g. I have a demo plugin that states in the plugin descriptor:

* since-build: 223
* until-build: 241.*

These values are used in the `patchPluginXml`. Then, I will get the following verification targets:

- IC-223.8836.26
- IC-231.9414.13
- IC-232.10300.40
- IC-233.15026.9
- IC-241.17011.2

@philCryoport, from your description, I assume you would like to verify against all point releases, right?

@hsz please confirm the behavior of the Gradle IntelliJ Plugin 1.x.

**Comment by philCryoport** [comment]
> Let's focus on the 1.x now.

👍

> 
> Plugin Verifier is behaving correctly. However, when you leave out the `since-build` and `until-build`, you'll get the verification against most recent builds in each Platform version.
> 
> E. g. I have a demo plugin that states in the plugin descriptor:
> 
>     * since-build: 223
> 
>     * until-build: 241.*
> 
> 
> These values are used in the `patchPluginXml`. Then, I will get the following verification targets:
> 
>     * IC-223.8836.26
> 
>     * IC-231.9414.13
> 
>     * IC-232.10300.40
> 
>     * IC-233.15026.9
> 
>     * IC-241.17011.2
> 
> 
> @philCryoport, from your description, I assume you would like to verify against all point releases, right?

Yes please!

* 2022.3 and its patch releases
* 2023.x.y -- major, minor, and patch releases
* 2024.x.y -- major, minor, and patch releases

**Comment by novotnyr** [comment]
@hsz please note that even the `listProductReleases` is acting in a non-obvious way.

```
    listProductsReleases {
        sinceVersion = "2023.3.1"
        untilVersion = "2023.3.6"
    }
```

Emits:

```
IC-2023.3.6
```

I would expect that it should list all point releases between `.1` and `.6`.

**Comment by philCryoport** [comment]
Following up with @hsz / @YannCebron : any thoughts on @novotnyr 's comment above that "[even the `listProductReleases` is acting in a non-obvious way](https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1510#issuecomment-2111699073)"?

**Comment by YannCebron** [comment]
AFAIU the explanation is that intermediate bugfix updates are no longer relevant, thus only the latest bugfix release is included (assuming all users update to latest bugfix updates always).

**Comment by philCryoport** [comment]
> AFAIU the explanation is that intermediate bugfix updates are no longer relevant, thus only the latest bugfix release is included (assuming all users update to latest bugfix updates always).

Ok I can kind of understand that

**Comment by YannCebron** [comment]
Can we close this issue then?
