### ISSUE TITLE
build.gradle: provide a way to set plugin's id and name when building the plugin

### ISSUE THREAD

**Issue by jonathanlermitage** [JetBrains/intellij-platform-gradle-plugin#1526]
### Describe the need of your request

For now, I can set the version in my build.gradle.kts:  
```
intellij {
    version.set(...)
}
```
-> I would need to do similar thing for the plugin `id` and `name`.  

### Proposed solution

Be able to use something like 
```
intellij {
    id.set(...)
    name(...)
}
```

### Additional context

Context: I will offer multiple editions of my plugin, and each edition it published as an independent plugin. They share the same code base, I don't want to maintain multiple git branches (too much work), but some features simply depend on the plugin's id. This is why I would like to set the plugin's `id` and `name` when I build the plugin. Thanks,

**Comment by hsz** [comment]
Thanks for filing this issue. This has already been implemented within the 2.0 version. It'll be possible to do with:

```
intellijPlatform {
    pluginConfiguration {
        id = "..."
        name = "..."
    }
}
```
