### ISSUE TITLE
JbrResolver resolved jbr 21 to vanilla jbr instead of jcef jbr #278

### ISSUE THREAD

**Issue by shalom938** [JetBrains/intellij-platform-gradle-plugin#1534]
### What happened?

JbrResolver resolved jbr 21 to vanilla jbr instead of jcef jbr.

when developing plugins with intellij 2024.1 EAP the IDE is downloaded with non jcef jbr and jcef is not supported.

### Steps to reproduce

runIde in a plugin project with platform version 2024.1 EAP

### Gradle IntelliJ Plugin version

1.17.0

### Gradle version

8.5

### Operating System

Linux

**Comment by hsz** [comment]
Obsolete in 2.0

**Comment by Jonatha1983** [comment]
@hsz not sure about opening a new ticket but I am having the same issue above.

I defined this in my build gradle:
```
dependencies {
  intellijPlatform {
    create(providers.gradleProperty("platformType"), providers.gradleProperty("platformVersion"), useInstaller = false)
    bundledPlugins(providers.gradleProperty("platformBundledPlugins").map { it.split(',') })
    jetbrainsRuntimeExplicit("jbr_jcef-21.0.4-osx-aarch64-b620.4")
```
and when running the runIde task the IDE that is opened is this (no jcef) 
```
IntelliJ IDEA 2025.1 Beta (Community Edition)
Build #IC-251.23774.109, built on March 13, 2025
Source revision: ae7cc8219e003
Runtime version: 21.0.4+8-b620.4 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.4
Kotlin plugin: K2 mode
Kotlin analyzer version: 2.2.0-dev-6100
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  llm.show.ai.promotion.window.on.start=false
Non-Bundled Plugins:
  com.gafner.azd (2025.1.17)
Kotlin: 251.23774.109-IJ
```
I am using:
``` intelliJPlatform = "2.3.0"```
This is what I am targeting:
```
pluginSinceBuild=251.21418.62
pluginUntilBuild=251.*
# IntelliJ Platform Properties -> https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#intellij-extension
platformType=IC
platformVersion=251-EAP-SNAPSHOT
```


am I doing something wrong?

**Comment by hsz** [comment]
@Jonatha1983 I've setup exactly the same environment. IDE shows no JCEF signs in the About dialog, but it actualy points to the correctly resolved JBR:

<img width="1421" alt="Image" src="https://github.com/user-attachments/assets/1fc3f9d7-9705-4c71-aa80-99c043396d92" />

**Comment by Jonatha1983** [comment]
@hsz and you can see jcef is working ? 
For me is not

**Comment by Jonatha1983** [comment]
By the way I don't think Java home is what you need to print because Java home can be set in one global place but that doesn't mean it is the jdk used by the ide

**Comment by hsz** [comment]
Unfortunately, #1906 has not yet been addressed; I'll prioritize it now.
