### ISSUE TITLE
Add IC-LATEST-STABLE and IU-LATEST-STABLE values for intellij.version property

### ISSUE THREAD

**Issue by jonathanlermitage** [JetBrains/intellij-platform-gradle-plugin#1547]
### Describe the need of your request

Like `IC-LATEST-EAP-SNAPSHOT`, it would be nice to have a flag like `IC-LATEST-STABLE` (and `IU-LATEST-STABLE`) in order to use the latest stable IJ release (today, it would be "IC-2023.3.4").

### Proposed solution

Be able to declare something like this in `build.gradle.kts`:  
```
intellij {
    version.set("IC-LATEST-STABLE")
}
```

### Alternatives you've considered

For now, I implemented this in my gradle build: https://github.com/jonathanlermitage/intellij-extra-toolwindow-colorful-icons/blob/main/build.gradle.kts#L231-L258  
But I think this feature could be integrated into the gradle-intellij-plugin project.

### Additional context

I used to test my plugins with 3 versions: 
- minimal IDE version (hard-coded, as it depends on my own plugin)
- **latest stable version** (idealy, something like `IC-LATEST-STABLE`). I am also using this version when developing in my IDE
- latest EAP snapshot (`IC-LATEST-EAP-SNAPSHOT`)

**Comment by jonathanlermitage** [comment]
I'm not sure to understand. LATEST-EAP-SNAPSHOT is even less stable.  
Just to explain how I work: I do my best to test my plugins with a minimal IDE version, and a maximum IDE version, which is the latest stable build. EAP builds can break (these are EAP, after all), I will check that *later*.  
Also, because I maintain some (8) plugins, I don't want to update my projects every time a new stable IDE build is available. This is so boring. A value like LATEST-STABLE is useful.
 
Some plugin developers asked on Slack how to get the latest stable build number. I believe it would help some of us. I don't know if this is a very common use case, but it exists, and it seems valid.

**Comment by YannCebron** [comment]
EAPs are provided for these two reasons:

a) check compatibility of existing plugins
b) explore/start using new API before GA

There is no _need_ to build your plugins against the latest GA, unless you explicitly need its features/bugfxes in your plugin.

**Comment by YannCebron** [comment]
You can use this to determine latest builds

https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-faq.html#how-to-check-the-latest-available-eap-release
