### ISSUE TITLE
Poor cacheability of `test` task

### ISSUE THREAD

**Issue by jhonnen** [JetBrains/intellij-platform-gradle-plugin#1554]
### What happened?

When executing the `test` task on an IntelliJ plugin on two different machines with the same source code, the task inputs are often different, causing Build Cache misses:
![Screenshot 2024-03-08 112309](https://github.com/JetBrains/gradle-intellij-plugin/assets/208302/6fe02b56-392e-4244-9f6a-c9a09ba21840)

The following task inputs differ:
* `build/tmp/initializeIntelliJPlugin/coroutines-javaagent.jar`
  * the jar has the same content but its entries have different timestamps (i.e. jar is not build reproducibly)
* `ideaIC-2023.2-2-withKotlin.xml`
  * this ivy module is generated with a current timestamp: https://github.com/JetBrains/gradle-intellij-plugin/blob/cc828c20fb7b4aba9cb6c190148581efabb10bda/src/main/kotlin/org/jetbrains/intellij/IntelliJIvyDescriptorFileGenerator.kt#L118
* `classpath.index`
  * in one build this file was not generated, I don't know why

### Steps to reproduce

Execute `test` on different machines with same sources (requires Gradle Enterprise for Build Cache).

### Gradle IntelliJ Plugin version

1.17.1

### Gradle version

8.6

### Operating System

Windows

**Comment by hsz** [comment]
Thanks for reporting!
- `coroutines-javaagent.jar` problem is already resolved in `2.0.0-beta9`. The file exists now directly in `build/` directory.
- `ideaIC-2023.2-2-withKotlin.xml` — XML files are no longer created within the Gradle cache in `2.0` due to the general depndency/repository management refactoring
- same about `classpath.index` files

Could you please give it a try? In terms of any new findings — please file a new issue. Thank you!

**Comment by blorente** [comment]
@hsz Thanks for the update!

We've observed that the file `coroutines-javaagent.jar` exists, but they still have different timestamps. It seems that the jars are using a relative path normalization strategy ([link](https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/4e58259843ceeb4314a8d53cd72404c2f8b62bb8/src/main/kotlin/org/jetbrains/intellij/platform/gradle/argumentProviders/IntelliJPlatformArgumentProvider.kt#L37)), which does take into account timestamps.

Maybe changing them to be considered classpath entries ([link](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Classpath.html)) could help here.
