### ISSUE TITLE
The dependency on the Kotlin Standard Library (stdlib) is automatically added when using the Gradle Kotlin plugin and may conflict with the version provided with the IntelliJ Platform

### ISSUE THREAD

**Issue by nbransby** [JetBrains/intellij-platform-gradle-plugin#1572]
The page linked in this warning (https://jb.gg/intellij-platform-kotlin-stdlib) doesn't actually detail how to resolve the warning, how are you suppose to remove the dependency?

**Comment by hsz** [comment]
It's explicitly written in the section you linked. Use:

```
kotlin.stdlib.default.dependency = false
```

**Comment by nbransby** [comment]
I got the impression that's just to disable the warning, I don't want to include the stdlib in my plugin, how do I exclude it?

**Comment by nbransby** [comment]
Ok I re-read it and realized `kotlin.stdlib.default.dependency` is a kotlin compiler option to exclude stdlib, first time I read it I thought it was a intellij-platform-gradle-plugin property just to prevent the warning. 

Perhaps that could be a little clearer in the docs or maybe I was just having a slow day!
