### ISSUE TITLE
The Kotlin Coroutines library should not be added explicitly to the project as it is already provided with the IntelliJ Platform.

### ISSUE THREAD

**Issue by nbransby** [JetBrains/intellij-platform-gradle-plugin#1573]
The page linked in this warning (https://jb.gg/intellij-platform-versions) doesn't actually detail how to resolve the warning, how are you supposed to remove the dependency when its added via a sub dependency (most kotlin libs rely on coroutines)?

**Comment by hsz** [comment]
You have to exclude `org.jetbrains.kotlinx:kotlinx-coroutines` from transitive dependencies.

See: https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:excluding-transitive-deps

**Comment by nbransby** [comment]
Thanks. I was doing it a different way which removes the lib but doesn't prevent the warning:
```
configurations.implementation {
    exclude("org.jetbrains.kotlinx", "kotlinx-coroutines")
 }
```
