### ISSUE TITLE
Hints not working

### ISSUE THREAD

**Issue by tatosgr** [JetBrains/intellij-platform-gradle-plugin#1578]
### What happened?

When I click the Hints, nothing happens. I know what should happen because they worked at the beginning of the course, now they don't work at all.

I don't know when they started to fail because there were several lessons when I didn't use them, but now that I want to use them, I can't.

I'm currently on "Mastermind - countExactMatches Function", if that helps.

https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/2810047/55ba0094-c2ac-41cd-86d3-bb6078861710

Also, when I click on Log in, nothing happens.

### Steps to reproduce

Build #AI-232.10300.40.2321.11567975, built on March 13, 2024

Runtime version: 17.0.9+0--11185874 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

### Gradle IntelliJ Plugin version

2024.2-2023.2-2218

### Gradle version

8.3

### Operating System

Windows

**Comment by hsz** [comment]
This issue is not related to the Gradle IntelliJ Plugin for Gradle build system but Educational plugin.

Reposted to: https://youtrack.jetbrains.com/issue/EDU-6763/Hints-not-working

**Comment by annmer** [comment]
Hello @tatosgr !

As it is mentioned above, a separate ticket was created for your issue in our `YouTrack`: https://youtrack.jetbrains.com/issue/EDU-6763/Hints-not-working

However, there are still several points that are missing to have the whole picture clearer for us.

1) Please ensure that your `JetBrains Academy` plugin is up to date (`File || Settings || Plugins`), if no - please update it, restart your IDE and check if the issue still persists. Then please specify this together with your plugin version in the comments to **`YouTrack` ticket mentioned above**.
2) Please attach the IDE logs to **`YouTrack` ticket mentioned above**. You can get the logs by selecting `Collect Logs and Diagnostic Data` from the `Help` menu.
3) Please attach an archive of the affected project directory to **`YouTrack` ticket**.
4) Also, I can see that when you click on `Log in`, nothing happens. If the issue still persists, **in the comments to `YouTrack` ticket** please specify where exactly you try to log in. It would be great if you could attach a screenshot or a screencast.

Thank you!
