### ISSUE TITLE
Incorrect JarSearchableOptionsTask Caching Behavior

### ISSUE THREAD

**Issue by tylerbertrand** [JetBrains/intellij-platform-gradle-plugin#1583]
### What happened?

The `jarSearchableOptions` task is exhibiting a cache miss caused by its `sandboxDir` input property being set to an absolute path. Since `sandboxDir` is a `String` property, the path it is set to should either be relative, or, if changes to the contents of the directory affect the outcome of the task, `sandboxDir` should be converted to a `DirectoryProperty` with relative path normalization, so that its contents can be properly tracked by Gradle.

### Relevant log output or stack trace

* [Task input comparison](https://ge.solutions-team.gradle.com/c/jwyvc7gbzhweq/jd2eqzlhesgkg/task-inputs?cacheability=cacheable,overlapping-outputs,validation-failure#xe75gobiwbnmu-sandboxdir) showing `sandboxDir` input difference
* [Custom value comparison](https://ge.solutions-team.gradle.com/c/jwyvc7gbzhweq/jd2eqzlhesgkg/custom-values#sandboxdir-11) showing the `sandboxDir` input difference is caused by an absolute path

### Steps to reproduce

In a project using `gradle-intellij-plugin`, run a clean build executing the `jarSearchableOptions` task. Clone or copy the project into another file system location, and run the same build again. The `jarSearchableOptions` task in the second build should come from cache, but it does not.

### Gradle IntelliJ Plugin version

1.17.3

### Gradle version

8.7-rc-1

### Operating System

None

**Comment by tylerbertrand** [comment]
I noticed that on the `main` main branch, the `JarSearchableOptionsTask` has been restructured to be `SandboxAware`, and that the `sandboxDir` property no longer exists - looks like it has been split into multiple `@Internal DirectoryProperty`s. In that case, not sure if you will want to fix the existing implementation, but based upon the updated implementation, perhaps `sandboxDir` should just be marked `@Internal`?

**Comment by hsz** [comment]
Thanks for your input, Tyler! And sorry for the pretty late reply ;-)

The sandbox story in `2.0` faced a couple of iterations and currently it's indeed `Internal`. The `prepareSandbox` task (the "sandbox producer") has in addition the `sandboxDirectory` path set as an input property (`String`, to do not consider its content)

https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/fe3be513ad3ff265fae1d255662b27b369f253b9/src/main/kotlin/org/jetbrains/intellij/platform/gradle/tasks/PrepareSandboxTask.kt#L316

Creating of all subdirectories within the sandbox is now also properly handled and tested.
