### ISSUE TITLE
Allow specifying scope of plugin dependency

### ISSUE THREAD

**Issue by Undin** [JetBrains/intellij-platform-gradle-plugin#1586]
### Describe the need of your request

In 2.0 plugin dependencies on IDE and IDE plugins will be reworked to be much closer to regular library dependencies.
But as I can see, it's still impossible to adjust the scope of such dependencies like you can usually do with other libraries like via `implementation`, `testImplementation`, etc. and provide dependency for production code, only for tests, etc.

It would be nice to have this option in 2.0 plugin version, especially taking into account already applied changes in dependency management.

My usecase why I need this - JetBrains Academy plugin has integration with CLion to support C++ courses. The support doesn't require any knowledge about C++ language itself (from PSI point of view), so the plugin doesn't need the corresponding dependency in production code. Moreover, at the moment of writing CLion is experimenting with a new language engine, so there are two different mutually exclusive plugins with different language engines which provide different PSI for the same code. And we **don't have** to have dependency on any of them to be able to work with any of them.
But at the same time, we have tests where we need some PSI for C++ code (like in production). So we **have to enable** a plugin which provides PSI for C++.
At the moment of writing, it's impossible to achieve both points (i.e. not having language plugin in production code and have a language plugin in tests). So currently we have a dependency on one of C++ language plugin in production code as well and have to manually keep an eye on not having actual dependency on code from this plugin in production code. With described features, it would be achieved automatically by providing test only plugin

### Proposed solution

Allow using `implementation`, `testImplementation` and other configuations where the corresponding plugin classes should be available

**Comment by YannCebron** [comment]
looks like #1387

**Comment by Undin** [comment]
> looks like #1387

Indeed. Feel free to close it as duplicate, but I think the proposed solution direction in this issue is much closer to an actual final solution than described in #1387

**Comment by hsz** [comment]
Since IntelliJ Platform Gradle Plugin `2.0.0`, it's possible to define custom test tasks and disable bundled plugins:

```
val customRunIde by intellijPlatformTesting.runIde.registering {
    type = IntelliJPlatformType.Rider
    version = "2024.2"

    plugins {
        plugin("pluginId:version")
        plugin(pluginId, version, channel)
        disablePlugins(bundledPlugiId)
    }
}

val customTest by intellijPlatformTesting.testIde.registering {
    ...
}
```

**Comment by Undin** [comment]
@hsz but as I understand, it's still not possible to customize common test task, right? If so, I don't need a separate test task - it's too inconvenient to use it. I just want to set up common `test` task with some specific plugins as test dependencies. Otherwise, running tests from IDE won't work as I want

**Comment by hsz** [comment]
@Undin  The main `test` as well as `runIde` and other default tasks are supposed to be run against the IntelliJ Platform set in dependencies and its default plugins listing.

**Comment by AlexanderBartash** [comment]
I would say not to do this, because it does not reflect true runtime environment. We have to remember that these plugins are run inside IDE ecosystem, where 1) some libs are always present, and it does not matter if plugin devs like it or not 2) some plugins are present or not 3) there are also modules but I do not understand them, not enough docs on that.

**Comment by AlexanderBartash** [comment]
Maybe it would be better to allow that test framework thing to turn on or off plugins from tests instead of doing this in Gradle?
