### ISSUE TITLE
Spring Boot Plugin: bootJar does not work when you change default excludes only in IJ Plugin

### ISSUE THREAD

**Issue by christopherpicard** [JetBrains/intellij-platform-gradle-plugin#1590]
### What happened?

Currently the plugin fails to run the bootJar with the following error:

Execution failed for task ':app-docker:bootJar'.

    Cannot change default excludes during the build. They were changed from [**/##, **/%%, **/~, **/.#, **/.DS_Store, **/., **/.bzr, /.bzr/, **/.bzrignore, **/.cvsignore, **/.git, /.git/, **/.gitattributes, **/.gitignore, **/.gitmodules, **/.hg, /.hg/, **/.hgignore, **/.hgsub, **/.hgsubstate, **/.hgtags, **/.svn, /.svn/, **/CVS, /CVS/, **/SCCS, /SCCS/, /vssver.scc] to [/##, **/%%, **/~, **/.#*, **/.DS_Store, **/.*, **/.bzr, /.bzr/, **/.bzrignore, **/.cvsignore, **/.git, /.git/, **/.gitattributes, **/.gitmodules, **/.hg, /.hg/, **/.hgignore, **/.hgsub, **/.hgsubstate, **/.hgtags, **/.svn, /.svn/, **/CVS, /CVS/, **/SCCS, /SCCS/, **/vssver.scc]. Configure default excludes in the settings script instead.

However, if you run the same task from the command line using the same gradle wrapper it works.

### Relevant log output or stack trace

```shell
Execution failed for task ':app-docker:bootJar'.
> Cannot change default excludes during the build. They were changed from [**/#*#, **/%*%, **/*~, **/.#*, **/.DS_Store, **/._*, **/.bzr, **/.bzr/**, **/.bzrignore, **/.cvsignore, **/.git, **/.git/**, **/.gitattributes, **/.gitignore, **/.gitmodules, **/.hg, **/.hg/**, **/.hgignore, **/.hgsub, **/.hgsubstate, **/.hgtags, **/.svn, **/.svn/**, **/CVS, **/CVS/**, **/SCCS, **/SCCS/**, **/vssver.scc] to [**/#*#, **/%*%, **/*~, **/.#*, **/.DS_Store, **/._*, **/.bzr, **/.bzr/**, **/.bzrignore, **/.cvsignore, **/.git, **/.git/**, **/.gitattributes, **/.gitmodules, **/.hg, **/.hg/**, **/.hgignore, **/.hgsub, **/.hgsubstate, **/.hgtags, **/.svn, **/.svn/**, **/CVS, **/CVS/**, **/SCCS, **/SCCS/**, **/vssver.scc]. Configure default excludes in the settings script instead.
```

### Steps to reproduce

Create a project that uses gradle plugin id 'org.springframework.boot' version '3.2.4'.

Add the following to the projects setting.gralde file:

- import org.apache.tools.ant.DirectoryScanner

- DirectoryScanner.removeDefaultExclude('**/.gitignore')

Run bootJar gradle task using intellij plugin.

### Gradle IntelliJ Plugin version

241.14494.240

### Gradle version

8.5

### Operating System

Windows

**Comment by hsz** [comment]
How is this issue related to the IntelliJ Platform Gradle Plugin?

**Comment by christopherpicard** [comment]
Because it only fails when I run the task using the Intellij Platform Gradle Plugin. If you run it from the command line using the same version of gradle it works as expected.

**Comment by hsz** [comment]
You mislead it with the Gradle plugin for IntelliJ IDEA.

This project is a plugin for the Gradle build system, used for developing plugins.

**Comment by hsz** [comment]
Please file an issue in YouTrack, in the IntelliJ IDEA project:

https://youtrack.jetbrains.com/newIssue?project=IDEA
