### ISSUE TITLE
org.gradle.configuration-cache = true results in JavaLauncherValueSource' has changed.

### ISSUE THREAD

**Issue by joshuataylor** [JetBrains/intellij-platform-gradle-plugin#1593]
### What happened?

`gradle.properties`:
```
org.gradle.configuration-cache = true
```

Results in this when doing a `./gradlew build` (Gradle 8.7):

```
Calculating task graph as configuration cache cannot be reused because a build logic input of type 'JavaLauncherValueSource' has changed.
```

### Relevant log output or stack trace

```shell
Not sure what or which log to give.
```

### Steps to reproduce

1. Use 2.0.0-beta1
2. Change `org.gradle.configuration-cache` to `true` in `gradle.properties`.
3. `./gradlew build` twice.

### Gradle IntelliJ Plugin version

2.0.0-beta1

### Gradle version

8.7

### Operating System

Linux

**Comment by hsz** [comment]
Thank you for reporting! The fix will be available in `-beta2`
