### ISSUE TITLE
Cannot download Android Studio 2023.2.1.25

### ISSUE THREAD

**Issue by Undefined-User** [JetBrains/intellij-platform-gradle-plugin#1612]
### What happened?

2023.2.1.25 is "Iguana | 2023.2.1 Patch 2" can find in https://developer.android.com/studio/archive

### Relevant log output or stack trace
```
Cannot resolve Android Studio with provided version: 2023.2.1.25
```

### Steps to reproduce

```
intellij {
    version = "2023.2.1.25"
    type = "AI"
    plugins = ["android"]
}
```

### Gradle IntelliJ Plugin version

-

### Gradle version

-

### Operating System

None

**Comment by YannCebron** [comment]
What is the version of Gradle plugin you're using?

**Comment by Undefined-User** [comment]
> What is the version of Gradle plugin you're using?

1.17.3, I can't find this version at that time in https://jb.gg/android-studio-releases-list.xml, but I can see it now.
