### ISSUE TITLE
Document `DownloadAndroidStudioProductReleasesXmlTask.releasesUrl` and `DownloadIdeaProductReleasesXmlTask.releasesUrl

### ISSUE THREAD

**Issue by mr-thierry** [JetBrains/intellij-platform-gradle-plugin#1613]
### Describe the need of your request

There is no example nor mention of `DownloadAndroidStudioProductReleasesXmlTask.releasesUrl` and `DownloadIdeaProductReleasesXmlTask.releasesUrl` in the documentation

### Proposed solution

Add a `buildScript` example of `DownloadAndroidStudioProductReleasesXmlTask.releasesUrl` and `DownloadIdeaProductReleasesXmlTask.releasesUrl`

**Comment by mr-thierry** [comment]
My proposed solution would be to add to the doc:

```
tasks.withType<DownloadAndroidStudioProductReleasesXmlTask>().configureEach {
    releasesUrl = "https://your.internal.server/android-list.xml"
}

```

**Comment by YannCebron** [comment]
Note this affects 1.x only which is now in maintenance mode.

**Comment by hsz** [comment]
This is not planned to be addressed in 1.x;
For 2.0, it is now possible to configure those URLs as described here: https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1686#issuecomment-2221297523
