### ISSUE TITLE
AndroidStudioDownloadLinkValueSource needs updating now that Google no longer publishes .zip for Mac

### ISSUE THREAD

**Issue by gharrma** [JetBrains/intellij-platform-gradle-plugin#1617]
### What happened?

Google is no longer publishing a .zip distro for Android Studio on Mac, because running from a .zip on Mac too easily triggers Gatekeeper / App Translocation, resulting in various runtime exceptions (usually related to VFS failing to find files within the IDE installation).

This appears to be consistent with JetBrains, in the sense that JetBrains does not offer Mac .zip distributions by default either: https://www.jetbrains.com/idea/download/other.html

To react, `AndroidStudioDownloadLinkValueSource.kt` would need to be updated to download the .dmg instead.

### Steps to reproduce

n/a

### Gradle IntelliJ Plugin version

n/a

### Gradle version

n/a

### Operating System

macOS

**Comment by hsz** [comment]
Implemented with https://github.com/JetBrains/intellij-platform-gradle-plugin/commit/6d260713e10fc6dc30383784195847e650210d29
