### ISSUE TITLE
2.0 - document how IDE sources are managed

### ISSUE THREAD

**Issue by jonathanlermitage** [JetBrains/intellij-platform-gradle-plugin#1629]
### Describe the need of your request

Using plugin v2  
According to https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-migration.html#intellijdownloadsources:
> Downloading sources is managed by the Plugin DevKit plugin in version 2024.1+.

What does it mean exactly? Does it download IDE's sources automatically for stable IDE versions, and not for EAP builds? (this is what I'm trying to do). Plugin v1 offered us to control that. If we lose control when switching to v2, a more detailed documentation would be helpful. Users may not want to download IDE sources when targeting an EAP build, and when running in a CI. I guess this is the default behavior, but I'm not sure. Thx.

### Proposed solution

Clarify documentation.

**Comment by jansorg** [comment]
Currently, with beta6 sources were neither downloaded for stable releases (IC-2024.1.1) nor for EAPs (`IC-242.15523.18-EAP-SNAPSHOT`). I've enabled `Gradle: Download sources` in the advanced settings. 
It's unclear to me if this is a bug or how I could control the download of sources. I very much would like to get sources for development...

**Comment by chylex** [comment]
IdeaVim has migrated to 2.0 and I can't figure out how to get sources to work either. I clicked "Download IntelliJ Platform sources", then I got this:

![obrazek](https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/3685160/62a34c51-c0a7-4634-a214-c5eb5e228199)

and clicking Yes did nothing. I reverted the commit to migrate to 2.0 in my IdeaVim fork, and sources got attached without any issues.

**Comment by jonathanlermitage** [comment]
Sources download no longer work for me. When I click the button in order to download platform's sources, I see this message, I accept, but it does nothing:
![image](https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/857535/82b09e19-3e8e-4e92-8eca-77cc6a8a2ed2)

**Comment by hsz** [comment]
To be fixed [IJPL-158473](https://youtrack.jetbrains.com/issue/IJPL-158473) and released in IntelliJ IDEA 2024.1.5 and 2024.2.

**Comment by hsz** [comment]
I tis now fixed with [IJPL-158473](https://youtrack.jetbrains.com/issue/IJPL-158473) and will be released in IntelliJ IDEA 2024.1.5 and 2024.2.

Docs are updated here: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html#attaching-sources
