### ISSUE TITLE
1.x: show instructions to use 2.x when targeting 242

### ISSUE THREAD

**Issue by YannCebron** [JetBrains/intellij-platform-gradle-plugin#1635]
### Describe the need of your request

Targeting 242 requires IntelliJ Platform Gradle Plugin 2.x
trying to use 1.x will fail with unclear errors

### Proposed solution

Show clear instructions and fail the build

**Comment by londonbrown** [comment]
Imo, a better approach would be to not have such an aggressive cutover to the new version in the first place. I see several problems:

## Confusing messaging
The [documentation](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html) has the following disconnected statements:
- [IntelliJ Platform Gradle Plugin 2.x (Beta)](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html) (currently in Early Access Preview) is going to replace this plugin in the future. **Please note that production usage is currently not recommended yet.**
- Gradle: Minimum Plugin Versions
  - When targeting 2024.2 or later, [IntelliJ Platform Gradle Plugin 2.x (Beta)](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html) is required.
  - When targeting 2022.3 or later, [Gradle IntelliJ Plugin](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#usage) version 1.10.1 or higher is required (current: 1.17.3)

### Analysis
- It's an early access preview, but also tagged as beta
- It's not recommended for production yet, but it will be required to target the next production release.

## Open questions
- What about `2024.2` makes it so different that it can't be supported in `1.x`? Did something dramatically change for `2024.2`?
- When will `2.x` be recommended for production use? 
  - Why is the only path for supporting `2024.2` to use an early access preview that isn't recommended for production yet?
- Is `gradle-intellij-plugin` (`1.x`) now considered abandonware? There was never any kind of announcement warning of this if so and the above requirements seem to suggest this.

**Comment by rybak** [comment]
> Targeting 242 requires IntelliJ Platform Gradle Plugin 2.x
> trying to use 1.x will fail with unclear errors

Agreed. It took me two and a half hours to figure it out. The problem is that I didn't even think to upgrade to newer version of 1.x 😕 I've just stumbled upon the 2.x requirement during the ordeal (#1638). Meaning that additional instructions in the output of 1.x wouldn't have helped me, unfortunately.

**Comment by YannCebron** [comment]
Please stick to the topic of this issue, a simple, unavoidable technical requirement to use 2.x when targeting 24.2 releases. Your feedback on 2.x is welcome in separate GH issues or join the Slack channel.

**Comment by PawelLipski** [comment]
Lemme open a separate issue for tracking the high-level concerns

**Comment by YannCebron** [comment]
Fixed in https://github.com/JetBrains/intellij-platform-gradle-plugin/releases/tag/v1.17.4
