### ISSUE TITLE
2.0 - could plugin 2024.2 EAP still be built with 1.x?

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/intellij-platform-gradle-plugin#1648]
Imo, a better approach would be to not have such an aggressive cutover to the new version in the first place. I see several problems:

## Confusing messaging
The [documentation](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html) has the following disconnected statements:
- [IntelliJ Platform Gradle Plugin 2.x (Beta)](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html) (currently in Early Access Preview) is going to replace this plugin in the future. **Please note that production usage is currently not recommended yet.**
- Gradle: Minimum Plugin Versions
  - When targeting 2024.2 or later, [IntelliJ Platform Gradle Plugin 2.x (Beta)](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html) is required.
  - When targeting 2022.3 or later, [Gradle IntelliJ Plugin](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#usage) version 1.10.1 or higher is required (current: 1.17.3)

### Analysis
- It's an early access preview, but also tagged as beta
- It's not recommended for production yet, but it will be required to target the next production release.

## Open questions
- What about `2024.2` makes it so different that it can't be supported in `1.x`? Did something dramatically change for `2024.2`?
- When will `2.x` be recommended for production use? 
  - Why is the only path for supporting `2024.2` to use an early access preview that isn't recommended for production yet?
- Is `gradle-intellij-plugin` (`1.x`) now considered abandonware? There was never any kind of announcement warning of this if so and the above requirements seem to suggest this.

_Originally posted by @londonbrown in https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1635#issuecomment-2140658082_

**Comment by PawelLipski** [comment]
> could plugin 2024.2 EAP still be built with 1.x?

I specifically selected this question for issue title as I think that providing support for building 2024.2-compatible plugins with 1.x would be satisfactory for most users. WDYT  @londonbrown @rybak?

**Comment by YannCebron** [comment]
2024.2 changed packaging of the IDE quite significantly, and given that all new features will only go to 2.x there is no point in adding 2024.2 support in 1.x.

1.x will continue to receive critical updates/fixes whenever needed. Migration to 2.x is highly advised (once it's GA) and will be a requirement when targeting 2024.2 or later.

2.x will be recommended for production use whenever it's ready, the plan is to have it ready when 2024.2 goes to Beta/RC status.

**Comment by PawelLipski** [comment]
Okay, thank you for clarification
