### ISSUE TITLE
runIde or CustomRunIdeTask can't override idea.* properties

### ISSUE THREAD

**Issue by jonathanlermitage** [JetBrains/intellij-platform-gradle-plugin#1651]
### What happened?

I would like to override the `idea.log.path` when running `runIde`, using plugin v2.  
My `build.gradle.kts` has:  

```
runIde {
    jvmArgs("-Didea.log.path=custom/logs/")
    jvmArgs("-Pidea.log.path=custom/logs/")
}
```
then run `gradlew runIde`.  

I also tried

```
register("myRunIde", CustomRunIdeTask::class) {
    jvmArgs("-Didea.log.path=custom/logs/")
    jvmArgs("-Pidea.log.path=custom/logs/")
}
```
then run `gradlew myRunIde`.

The logs are still located in the regular log folder (sandboxed dir / ide version / log). I checked the `idea.log.path` property with VisualVM, and they are no affected by my changes.  
Please note I tried to override both the JVM property and the System property, because when running `runIde` with no customization, I observed both properties are set.

### Steps to reproduce

*

### Gradle IntelliJ Plugin version

2.0.0-beta6

### Gradle version

8.8

### Operating System

Windows

**Comment by hsz** [comment]
All _runnable_ tasks are now working on `jvmArgumentProviders` to respect [Providers](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/Provider.html).
Apparently, values defined that way override _regular_ arguments passed with `jvmArgs()`.

To utilize `jvmArgumentProviders` in your setup, you can:

```kotlin
jvmArgumentProviders += CommandLineArgumentProvider {
    listOf("-Didea.config.path=custom/config")
}
```

FTR, with `beta9`, there's a new way of creating custom tasks introduced:

```kotlin
val myRunIde by intellijPlatformTesting.runIde.registering {
    // ...

    task {
        jvmArgumentProviders += CommandLineArgumentProvider {
            listOf("-Didea.config.path=custom/config")
        }
    }
}
```
