### ISSUE TITLE
2.0 - verifyPlugin still ignores some specified ides

### ISSUE THREAD

**Issue by ahus1** [JetBrains/intellij-platform-gradle-plugin#1658]
### What happened?

When I specify multiple IDEs for the verificatoin, only one seems to be selected.

This is a follow-up to issue #1637 which has been closed.

### Relevant log output or stack trace

```shell
Input:


pluginVerifierIdeVersions = IC-233.11361.10,IC-241.15989.150,IC-242.16677.21
```

Output

```
Scheduled verifications (1):
org.asciidoctor.intellij.asciidoc:0.41.16 against IC-241.15989.150
```

### Steps to reproduce

```
    verifyPlugin {
        ides {
            ides( provider { properties("pluginVerifierIdeVersions").get().split(',') } )
        }
    }
```

https://github.com/ahus1/asciidoctor-intellij-plugin/blob/upgrade-intellij-2024.2-jdk-21/build.gradle.kts

### Gradle IntelliJ Plugin version

2.0.0-beta7

### Gradle version

8.7

### Operating System

Windows

### Link to build, i.e. failing GitHub Action job

https://github.com/asciidoctor/asciidoctor-intellij-plugin/actions/runs/9529232258/job/26267748330?pr=1629

**Comment by PawelLipski** [comment]
+1, still not fixed for me either ☹️

**Comment by ahus1** [comment]
I was now able to run two verifications against IC-241.14494.240 and IC-241.15989.150. Thank you for the fix.

Verifying IC-242.x versions fails with a

> NoSuchFileException: C:\Users\ahus1\.gradle\caches\transforms-4\3147099be318dee8ba34ae2e034c12af\transformed\ideaIC-242.18071.24\plugins\emojipicker\lib\emojipicker.jar

Opened https://youtrack.jetbrains.com/issue/MP-6708 for that.
