### ISSUE TITLE
Bundled plugin sources are not available

### ISSUE THREAD

**Issue by ekudel** [JetBrains/intellij-platform-gradle-plugin#1672]
### What happened?

I cannot browse a source code of bundled plugins. Platform's sources are shown fine though. This didn't happen with the "old" plugin"

### Steps to reproduce

1. Create a plugin
2. Add IntelliJ dependency with Git plugin: `dependencies { intellijPlatform { intellijIdeaCommunity("242-EAP-SNAPSHOT"); bundledPlugins("Git4Idea") } }`
3. Perform "Reload All Gradle Projects"
4. Try to open `GitRepository` class.  The class file will be opened and the IDE will suggest to decompile it.

### Gradle IntelliJ Plugin version

2.0.0-beta7

### Gradle version

8.8.0

### Operating System

macOS

**Comment by hsz** [comment]
To be fixed [IJPL-158473](https://youtrack.jetbrains.com/issue/IJPL-158473) and released in IntelliJ IDEA 2024.1.5 and 2024.2.

**Comment by hsz** [comment]
I tis now fixed with [IJPL-158473](https://youtrack.jetbrains.com/issue/IJPL-158473) and will be released in IntelliJ IDEA 2024.1.5 and 2024.2.
