### ISSUE TITLE
2.0.0-beta8 - `verifyPlugin` warns about extending interfaces with `@NonExtendable` methods (rather than overriding these methods)

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/intellij-platform-gradle-plugin#1676]
### What happened?

[Interface `com.intellij.openapi.actionSystem.DataContext` (link)](https://sourcegraph.com/github.com/JetBrains/intellij-community/-/blob/platform/core-ui/src/openapi/actionSystem/DataContext.java) has the following two methods:

```java
@Nullable Object getData(@NotNull String dataId);

@ApiStatus.NonExtendable
default @Nullable <T> T getData(@NotNull DataKey<T> key) { ... }
```

I understand from the `NonExtendable` annotation that `getData(DataKey<T>)` should **not** be extended, and `getData(String)` can be extended instead.

Plugin verifier, however, warns about classes that extend the interface, even if they only override the non-`NonExtendable` method. It says `This interface is marked with @org.jetbrains.annotations.ApiStatus.NonExtendable, which indicates that the interface is not supposed to be extended`, which AFAICS isn't true &mdash; the interface is (quite reasonably) meant to be extended, one of its methods isn't.

I'm not sure if that's the issue with `intellij-platform-gradle-plugin` or with plugin verifier itself &mdash; pls lmk if the latter and I'll open this issue in a different repo.

### Relevant log output or stack trace

```shell
Non-extendable API usages (2):
    #Non-extendable interface com.intellij.openapi.actionSystem.DataContext is implemented
        Non-extendable interface com.intellij.openapi.actionSystem.DataContext is implemented by com.virtuslab.gitmachete.frontend.ui.impl.table.UnmanagedBranchNotificationFactory$1. This interface is marked with @org.jetbrains.annotations.ApiStatus.NonExtendable, which indicates that the interface is not supposed to be extended. See documentation of the @ApiStatus.NonExtendable for more info.
        Non-extendable interface com.intellij.openapi.actionSystem.DataContext is implemented by com.virtuslab.gitmachete.frontend.ui.impl.table.UnmanagedBranchNotificationFactory$2. This interface is marked with @org.jetbrains.annotations.ApiStatus.NonExtendable, which indicates that the interface is not supposed to be extended. See documentation of the @ApiStatus.NonExtendable for more info.
```

### Steps to reproduce

Check out https://github.com/VirtusLab/git-machete-intellij-plugin, run `./gradlew verifyPlugin` &mdash; you should get the warnings as above. The affected [anonymous classes](https://github.com/VirtusLab/git-machete-intellij-plugin/blob/v5.0.0/frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/table/UnmanagedBranchNotificationFactory.java#L81) look like:

```java
              val dataContext = new DataContext() {
                @Override
                public @Nullable Object getData(String dataId) { ... }
              };
```

### Gradle IntelliJ Plugin version

2.0.0-beta8

### Gradle version

8.8

### Operating System

macOS

**Comment by abrooksv** [comment]
The entire interface is marked as NonExtendable: https://sourcegraph.com/github.com/JetBrains/intellij-community/-/blob/platform/core-ui/src/openapi/actionSystem/DataContext.java?L38

Your use case looks like it should be using `https://github.com/JetBrains/intellij-community/blob/0f0277f3af77ea22ed5ed07222fbee9bc45b239b/platform/editor-ui-api/src/com/intellij/openapi/actionSystem/CustomizedDataContext.java#L107`

**Comment by PawelLipski** [comment]
Ouch, I was probably looking at the old sources. Makes sense, closing the ticket

**Comment by PawelLipski** [comment]
Actually @abrooksv... where should I take the `parent` DataContext from (to pass as the first param to `CustomizedDataContext.withProvider`) to keep parity with the existing `new DataContext()`-based implementation? should it be just replaced with something like `DataManager.getInstance().getDataContext()`?
