### ISSUE TITLE
Task buildSearchableOptions does not work properly with IntelliJ 2024.2

### ISSUE THREAD

**Issue by gharrma** [JetBrains/intellij-platform-gradle-plugin#1688]
### What happened?

Running the task `jarSearchableOptions` with IntelliJ 2024.2 always results in the following warning:
```
[org.jetbrains.intellij.platform] No searchable options found. If the plugin does not provide custom settings, disable building searchable options to improve build performance. See: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-extension.html#intellijPlatform-buildSearchableOptions
```

This happens even when the plugin has searchable options that should be found.

Root cause: IntelliJ commit [fd74726f95](https://github.com/JetBrains/intellij-community/commit/fd74726f95b0ac0cb3889da30a241ce6bd8941cd) switched the searchable-options format from XML to JSON (among other things), but `JarSearchableOptionsTask` [still uses](https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/32465950a4cfd263ac9b4bb2b29193c6ec68a074/src/main/kotlin/org/jetbrains/intellij/platform/gradle/tasks/JarSearchableOptionsTask.kt#L22) the old XML file names.

To see what the new JSON file format looks like you can run the `buildSearchableOptions` task and then inspect the contents of `build/tmp/buildSearchableOptions/`. You should see various files like this:
```
...
p-ByteCodeViewer-searchableOptions.json
p-Coverage-searchableOptions.json
p-Git4Idea-searchableOptions.json
...
```

### Steps to reproduce

1. Set the IntelliJ version to `242.18071.24` (for example) in `build.gradle.kts`
2. Run `./gradlew jarSearchableOptions`
3. Notice the warning about "no searchable options found"

### Gradle IntelliJ Plugin version

2.0.0-beta8

### Gradle version

8.8

### Operating System

None

**Comment by hsz** [comment]
Thanks Matthew for all details.
The task is now adjusted + covered with tests for 242+.
