### ISSUE TITLE
No custom plugins in IDE running by custom `RunIde` task since beta8

### ISSUE THREAD

**Issue by Undin** [JetBrains/intellij-platform-gradle-plugin#1689]
### What happened?

Starting with beta8, all custom `runIde` tasks declared via `intellijPlatformTesting.runIde.register`, don't add plugins passed in `plugins` section.

As a result, I can't easily check IDE with all necessary plugins, which makes custom `RunIde` tasks much less useful during development

<img width="494" alt="Screenshot 2024-07-10 at 14 57 33" src="https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/2539310/9f4e0721-4613-4607-b2ae-0e5f5aa88a65">
<img width="455" alt="Screenshot 2024-07-10 at 14 52 45" src="https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/2539310/b45cd984-5b4b-497a-8852-ab8e6af8a5ed">
<img width="912" alt="Screenshot 2024-07-10 at 14 52 29" src="https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/2539310/fc2d7882-2c22-404e-a577-bb487eddbeea">

### Steps to reproduce

Clone https://github.com/Undin/intellij-platform-gradle-plugins-bugs/tree/no-custom-plugins-for-custom-runIde and run `:CustomRunIde` gradle task

### Gradle IntelliJ Plugin version

2.0.0-beta8

### Gradle version

8.7

### Operating System

macOS

**Comment by hsz** [comment]
Thanks for reporting! Fixed with https://github.com/JetBrains/intellij-platform-gradle-plugin/commit/11b2b7845a0a4c7d466b116efc16af639bd704f3
