### ISSUE TITLE
`signPlugin` fails with "No Marketplace ZIP Signer executable found"

### ISSUE THREAD

**Issue by InSyncWithFoo** [JetBrains/intellij-platform-gradle-plugin#1697]
### What happened?

I ran `publishPlugin` and got [this error](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/actions/runs/9924608225/job/27416092260):

```text
> Task :signPlugin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signPlugin'.
> No Marketplace ZIP Signer executable found.
  Please ensure the `zipSigner()` entry is present in the project dependencies section or `intellijPlatform.signing.cliPath` extension property
```

### Relevant details

I have all 4 secrets (`CERTIFICATE_CHAIN`, `PRIVATE_KEY`, `PRIVATE_KEY_PASSWORD` and `PUBLISH_TOKEN`) set; they are accessible to actions and worked in v1 runs. Also, I think the `intellijPlatform.signing` block is written correctly (the full build script can be found [here](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/blob/612c6f0ae05f56ee70ba3afd519c1b6a012f1af6/build.gradle.kts)):

```kotlin   
signing {
    certificateChain = environment("CERTIFICATE_CHAIN")
    privateKey = environment("PRIVATE_KEY")
    password = environment("PRIVATE_KEY_PASSWORD")
}
```

Environment:

* Plugin version: 2.0.0-beta9
* Gradle version: 8.9
* OS: Linux

**Comment by hsz** [comment]
Looking at your build script, you have no `zipSigner()` entry present. The exception is pretty descriptive.

>  Please ensure the `zipSigner()` entry is present in the project dependencies section or `intellijPlatform.signing.cliPath` extension property

**Comment by hsz** [comment]
In `v1`, all dependencies and custom repositories were added without your knowledge, which is against the rules of how Gradle plugins should work — that also breaks the [Centralizing repositories declaration](https://docs.gradle.org/current/userguide/dependency_management.html#sub:centralized-repository-declaration).

Docs are planned to be synced and enhanced next week.

And thanks for highlighting the Plugin Template — I'll add this entry there, I've missed that part there.

**Comment by hsz** [comment]
BTW — did this solve your problem?

**Comment by hsz** [comment]
Again — please read the exception thrown by the plugin. Did you make sure you have added `zipSigner()` entry in your dependencies?
Looking at your code, you didn't do that — which prevents you from signing the plugin.

**Comment by hsz** [comment]
Thanks for letting me know!
The plugin template is already updated.
I'll close the ticket as soon as documentation covers this topic.
Thank you for help on that!
