### ISSUE TITLE
sometimes getting error in build Could not resolve all files for configuration

### ISSUE THREAD

**Issue by shalom938** [JetBrains/intellij-platform-gradle-plugin#1704]
### What happened?

Execution failed for task ':rider:instrumentCode'.
> Could not resolve all files for configuration ':rider:intellijPlatformJavaCompiler'.
   > Could not resolve com.jetbrains.intellij.java:java-compiler-instrumentation-util:GOLAND-242.19890.15-EAP-SNAPSHOT.
     Required by:
         project :rider > com.jetbrains.intellij.java:java-compiler-ant-tasks:GOLAND-242.19890.15-EAP-SNAPSHOT
         project :rider > com.jetbrains.intellij.java:java-compiler-ant-tasks:GOLAND-242.19890.15-EAP-SNAPSHOT > com.jetbrains.intellij.java:java-gui-forms-compiler:GOLAND-242.19890.15-EAP-SNAPSHOT
         project :rider > com.jetbrains.intellij.java:java-compiler-ant-tasks:GOLAND-242.19890.15-EAP-SNAPSHOT > com.jetbrains.intellij.java:java-compiler-instrumentation-util-java8:GOLAND-242.19890.15-EAP-SNAPSHOT
      > Could not resolve com.jetbrains.intellij.java:java-compiler-instrumentation-util:GOLAND-242.19890.15-EAP-SNAPSHOT.
         > Could not get resource 'https://cache-redirector.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/java/java-compiler-instrumentation-util/GOLAND-242.19890.15-EAP-SNAPSHOT/java-compiler-instrumentation-util-GOLAND-242.19890.15-EAP-SNAPSHOT.pom'.
            > Could not GET 'https://cache-redirector.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/java/java-compiler-instrumentation-util/GOLAND-242.19890.15-EAP-SNAPSHOT/java-compiler-instrumentation-util-GOLAND-242.19890.15-EAP-SNAPSHOT.pom'. Received status code 502 from server: Bad Gateway
> There is 1 more failure with an identical cause.

### Steps to reproduce

fails on github, the error is not consistent. restart the job passes

### Gradle IntelliJ Plugin version

beta8

### Gradle version

8.8

### Operating System

Linux

**Comment by hsz** [comment]
Please start with upgrading to `2.0.0-rc1` and check of this issue still persist.

**Comment by shalom938** [comment]
OK, I will upgrade and follow our github actions.
Thank you
