### ISSUE TITLE
Duplicate caches take up disk space

### ISSUE THREAD

**Issue by Vanco** [JetBrains/intellij-platform-gradle-plugin#1705]
### What happened?

When used in a multi-module project, each module downloads an idea platform package, caches multiple versions of the same package, and quickly fills up disk space.

e.g. my project has ten module (Gradle subproject).  `ideaIC-2024.1.1-aarch64` has been cached many times.
![Screenshot 2024-07-22 at 08 55 15-2](https://github.com/user-attachments/assets/3243244e-9a17-47bb-bd0e-4e572827bc56)
![Screenshot 2024-07-22 at 08 53 09-2](https://github.com/user-attachments/assets/80b48cd0-15f5-4c68-aad6-cc5399a2153a)

### Steps to reproduce

1. import Gradle  project or runIde for a while
2. check the Gradle cache `USER_HOME/.gradle/cache/transforms-4/xxxxxxx/transformed/ideaXX-xxx`

### Gradle IntelliJ Plugin version

2.0.0-RC1

### Gradle version

8.7

### Operating System

macOS

**Comment by hsz** [comment]
Thanks for reporting. Toys was already reported in  #1601
