### ISSUE TITLE
ComposedJar task does not get run for submodules which are not using pluginModule dependency helper

### ISSUE THREAD

**Issue by AlexanderBartash** [JetBrains/intellij-platform-gradle-plugin#1713]
### What happened?

I have a plugin consisting of multiple gradle modues: 
- the main (parent) module
- a sub-module

The dependency from the parent module to the submodule is declared using `implementation(project(":submodule:"))` instead of `pluginModule(implementation(project(":submodule")))` because I do not want the jars to get merged.
 
I have code instrumentation enabled for all modules (really, I checked).

After I build the plugin with "buildPlugin" task in the resulting zip I see 
- main-module.jar (instrumented)
- submosude-base.jar (not instrumented) <<< It should be submodule.jar instead, generated by composedJar task

For the submodule the next tasks are run:
- :instrumentCode
- :jar

For the main module the next tasks are run:
- :instrumentCode
- :jar
- :instrumentedJar
- :composedJar

Also I see that only submodule-base.jar (not instrumented) is also get copied into the sandbox.

If I declare the dependency using  `pluginModule(implementation(project(":submodule")))`  it works as expected, i.e. composedJar task is run for the submodule and the correct jar is used.

### Steps to reproduce

- Create a plugin with a sub-module
- Declare the dependency using `implementation(project(":submodule:"))` instead of `pluginModule(implementation(project(":submodule")))`
- Enable code instrumentation in both modules by using `instrumentationTools()` helper & setting `instrumentCode` property to true.
- run `buildPlugin`

The expected result:
- `instrumentedJar` & `composedJar` tasks are run for both the submodule & the main module

The actual result:
- `instrumentedJar` & `composedJar` tasks are not run for the submodule

### Gradle IntelliJ Plugin version

2.0.0

### Gradle version

8.9

### Operating System

Linux

**Comment by hsz** [comment]
Thanks for reporting, Alexander!
Unfortunately, I'm unable to reproduce this issue. Could you please prepare a minimal project and publish it to GitHub so I could run it locally?

**Comment by AlexanderBartash** [comment]
@hsz I will try to set up something, but I think I've found the root case. There is one more crucial step required to reproduce it, but I will skip that for now and jump to the root case:

IntelliJPlatformModulePlugin incorrectly (well, correctly but not entirely) sets target JVM version for outgoing variant `intellijPlatformComposedJar` because instead:
```
attributeProvider(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, project.provider {
    project.the<JavaPluginExtension>().targetCompatibility.majorVersion.toInt()
})
```
It should probably do something like this:
[getDefaultTargetPlatform](https://github.com/gradle/gradle/blob/master/platforms/jvm/plugins-java-base/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmLanguageUtilities.java#L82)

It is necessary because target compatibility can be set in multiple ways:
1) This is what Intellij Platform plugin supports now:
```
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}
```
2) An alternative way supported by Gradle's [getDefaultTargetPlatform](https://github.com/gradle/gradle/blob/master/platforms/jvm/plugins-java-base/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmLanguageUtilities.java#L82) but not by this plugin:
```
tasks {
    // Set the JVM compatibility versions
    // Should be 1.7 otherwise it will not work in Hybris 5.X which require java 1.7.
    // But the source code uses 1.8 API, and it is unlikely that someone is using Hybris 5.x today.
    withType<JavaCompile> {
        sourceCompatibility = "1.8"
        targetCompatibility = "1.8"
    }

    kotlin {
        compilerOptions {
            jvmTarget = JvmTarget.JVM_1_8
        }
    }
```

So that missing step required to reproduce it is: you need to have JAVA_HOME set to JDK e.g. 22, while building the plugin for JDK 21. In such case `intellijPlatformComposedJar` variant will have "org.gradle.jvm.version" set to 22 (the value from JAVA_HOME, which is completely irrelevant to the project being built) instead of whatever was specified in the compiler options.

I will add more clear steps later, in case if this is confusing.

**Comment by AlexanderBartash** [comment]
Also it may be that https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/main/src/main/kotlin/org/jetbrains/intellij/platform/gradle/attributes/ComposedJarRule.kt has a mistake too, but I am not really sure regarding this one.

That rule says that producer's "jar" is compatible when a consumer requests "composed-jar".

It seems to me, that it should be the other way around.

**Comment by AlexanderBartash** [comment]
Relevant documentation https://docs.gradle.org/current/userguide/building_java_projects.html#sec:java_cross_compilation

**Comment by AlexanderBartash** [comment]
Closing because opened a new issue with more relevant details https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1772
