### ISSUE TITLE
add useInstaller to Ides extension ide helper method

### ISSUE THREAD

**Issue by shalom938** [JetBrains/intellij-platform-gradle-plugin#1715]
### Describe the need of your request

ide in ides extension doesn't accept useInstaller like create in dependencies extension. so can't use EAP here because there is no binary release. i see that ide always does
`useInstallerProvider = delegate.provider { true },`
this doesn't work:
`ide(IntelliJPlatformType.IntellijIdeaCommunity, "242-EAP-SNAPSHOT")`

this works, but its not enough because ide is mandatory
```
select {
                    types =
                        listOf(IntelliJPlatformType.IntellijIdeaCommunity, IntelliJPlatformType.IntellijIdeaUltimate)
                    channels = listOf(ProductRelease.Channel.EAP)
                    sinceBuild = "242"
                    untilBuild = "242.*"
                }
```

### Proposed solution

add useInstaller to ide extension like create in dependencies extension

### Alternatives you've considered

I use recommended() where possible

### Additional context

we build and verify the same branch with different platform version supplied as gradle property

**Comment by hsz** [comment]
Thanks for reporting. With the upcoming release, it'll be now possible to use non-installer IDEs with:

```kotlin
intellijPlatform {
    pluginVerification {
        ides {
            recommended()
            ide(IntelliJPlatformType.IntellijIdeaCommunity, "LATEST-EAP-SNAPSHOT", useInstaller = false)
        }
    }
}
```

<img width="1405" alt="image" src="https://github.com/user-attachments/assets/24beace1-3a6c-4801-aa9d-7764f4652b86">
