### ISSUE TITLE
The v2.0.0 fails to resolve a snapshot build of IntelliJ Platform

### ISSUE THREAD

**Issue by alshan** [JetBrains/intellij-platform-gradle-plugin#1716]
### What happened?

My plugin project at the moment depends on an IntelliJ platform snapshot build:
```
dependencies {
    intellijPlatform {
        intellijIdeaUltimate("242-EAP-SNAPSHOT")
...
```

This configuration is working fine with IntelliJ Platform Gradle Plugin v2.0.0-beta5.

With v2.0.0 however, the build fails with error: 
>  * What went wrong:
Could not determine the dependencies of task ':buildSearchableOptions'.
> Failed to query the value of task ':buildSearchableOptions' property 'runtimeDirectory'.
   > Could not resolve all files for configuration ':intellijPlatformDependency'.
      > Could not find idea:ideaIU:242-EAP-SNAPSHOT.
        Searched in the following locations:
          - https://download.jetbrains.com/idea/ideaIU-242-EAP-SNAPSHOT-aarch64.dmg
          - https://download.jetbrains.com/idea/ideaIU-242-EAP-SNAPSHOT.aarch64.dmg
          - https://download.jetbrains.com/idea/242-EAP-SNAPSHOT/ideaIU-242-EAP-SNAPSHOT-aarch64.dmg
          - https://download.jetbrains.com/idea/242-EAP-SNAPSHOT/ideaIU-242-EAP-SNAPSHOT.aarch64.dmg
        Required by:
            project :

  

### Steps to reproduce

Will provide if required.

### Gradle IntelliJ Plugin version

2.0.0

### Gradle version

8.9

### Operating System

macOS

**Comment by hsz** [comment]
See https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-dependencies-extension.html#target-versions

**Comment by alshan** [comment]
I'm not sure what exactly you are referring to. 
My setup is:
```
repositories {
    mavenCentral()

    intellijPlatform {
        defaultRepositories()
        jetbrainsRuntime()
    }
}

dependencies {
    intellijPlatform {
        intellijIdeaUltimate("242-EAP-SNAPSHOT")
        jetbrainsRuntime()
        instrumentationTools()
        plugin("Pythonid", "242.16677.21")
    }
...
```
where the snapshot artifact is specified as prescribed here:
https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html#specify-the-maven-coordinates-for-the-artifact

What's missing?

**Comment by hsz** [comment]
You need to use the `useInstaller = false` to use EAP releases as by default, it resolves non-EAP installers.
Remember to take care of JBR, as explained there.

Apparently the documentation isn't clear enough, I'll try to make it more clear.

**Comment by hfhbd** [comment]
Can you please describe where you should add the `useInstaller = false`?

**Comment by alshan** [comment]
Thank you guys, I can confirm that EAP dependency 

`intellijIdeaUltimate("242-EAP-SNAPSHOT", useInstaller = false)`

resolves perfectly.

Would be nice to drop a warning to the console in the 
`intellijIdeaUltimate("242-EAP-SNAPSHOT")` 
situation.
