### ISSUE TITLE
PrepareSandboxTask is missing outputs

### ISSUE THREAD

**Issue by jhonnen** [JetBrains/intellij-platform-gradle-plugin#1730]
### What happened?

When `prepareTestSandbox` is loaded FROM-CACHE, the `test` tasks fails because of missing input directories.

### Relevant log output or stack trace

```shell
* What went wrong:
A problem was found with the configuration of task ':test' (type 'Test').
  - Type 'org.gradle.api.tasks.testing.Test' property 'jvmArgumentProviders.$4.sandboxConfigDirectory' specifies directory '<projectDir>\build\idea-sandbox\IC-2024.1\config-test' which doesn't exist.

    Reason: An input file was expected to be present but it doesn't exist.
```

### Steps to reproduce

With build cache enabled, execute `gradlew prepareTestSandbox`, delete the build dir and run `gradlew test`.

-> `build/idea-sandbox/IC-2024.1/plugins-test` is correctly restored from cache, but not `config-test`

`PrepareSandboxTask` needs to declare all output directories it creates. Also it might make sense to disable caching anyway for this I/O-focused task.

### Gradle IntelliJ Plugin version

2.0.0

### Gradle version

8.9

### Operating System

None

**Comment by hsz** [comment]
I have fixed that with https://github.com/JetBrains/intellij-platform-gradle-plugin/commit/c278056545f6772d596b7d3512feaa0787eeb4f2

Could you please verify if this resolves the issue on your end?
You can use the 2.0.1-SNAPSHOT [snapshot release](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html#snapshot-release) for that.

**Comment by jhonnen** [comment]
disabling caching fixed the issue 👍
