### ISSUE TITLE
Dependency com.jetbrains.intellij.java:java-compiler-ant-tasks is missing

### ISSUE THREAD

**Issue by stackmagic** [JetBrains/intellij-platform-gradle-plugin#1734]
### What happened?

 com.jetbrains.intellij.java:java-compiler-ant-tasks can't be resolved. gradle tries to hit 

https://cache-redirector.jetbrains.com/intellij-dependencies/com/jetbrains/intellij/java/java-compiler-ant-tasks/maven-metadata.xml

which resolves to

https://packages.jetbrains.team/maven/p/ij/intellij-dependencies/com/jetbrains/intellij/java/java-compiler-ant-tasks/maven-metadata.xml

which returns a 404... 

### Relevant log output or stack trace

```shell
$ ./gradlew clean build --refresh-dependencies
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details
Calculating task graph as configuration cache cannot be reused due to --refresh-dependencies

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache state could not be cached: field `__javaCompilerConfiguration__` of task `:instrumentCode` of type `org.jetbrains.intellij.platform.gradle.tasks.InstrumentCodeTask`: error writing value of type 'org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection'
> Could not resolve all files for configuration ':intellijPlatformJavaCompiler'.
   > Could not find any matches for com.jetbrains.intellij.java:java-compiler-ant-tasks:{strictly [242, 242.20224.300]; prefer 242.20224.300} as no versions of com.jetbrains.intellij.java:java-compiler-ant-tasks are available.
     Searched in the following locations:
       - https://cache-redirector.jetbrains.com/intellij-dependencies/com/jetbrains/intellij/java/java-compiler-ant-tasks/maven-metadata.xml
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 16s
Configuration cache entry discarded due to serialization error.
```

### Steps to reproduce

git clone https://github.com/stackmagic/intellij-plugin
cd intellij-plugin
./gradlew clean build --refresh-dependencies

### Gradle IntelliJ Plugin version

2.0.0

### Gradle version

8.8

### Operating System

Linux

**Comment by hsz** [comment]
Those artifacts are available in `releases()` and _optionally_ `snapshots()` repositories.

**Comment by stackmagic** [comment]
Thanks! Adding releases() fixes everything when i build the project on an open network but ultimately, this should run in a closed network where everything must be fetched via a nexus server.

I've been experimenting a bit and I think the strategy would be to disable the cache-redirector and also intellijDependencies() and releases() in the repositories section to force lookups via nexus and mirror at least 2 additional repos:

- https://packages.jetbrains.team/maven/p/ij/intellij-dependencies
- https://www.jetbrains.com/intellij-repository/releases

Are there any other repositories I need to be aware of so the infra guys can do this in one go? Is there a jetbrains howto/manual for this scenario? I couldn't find anything useful on this.

**Comment by hsz** [comment]
All the repositories used by the plugin are defined as repository helpers here:
https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/main/src/main/kotlin/org/jetbrains/intellij/platform/gradle/extensions/IntelliJPlatformRepositoriesExtension.kt

Also note that or is possible to opt-out from using the cache redirector. See https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-gradle-properties.html#useCacheRedirector
