### ISSUE TITLE
Why did I add custom dependency and runide OK. But after installing the plug-in run error message 'custom dependency class not found'. Why!!!

### ISSUE THREAD

**Issue by zxuanhong** [JetBrains/intellij-platform-gradle-plugin#1737]
### What happened?

1. dependencies add 'org.apache.commons:commons-text:1.11.0'
<img width="1274" alt="image" src="https://github.com/user-attachments/assets/5f835a01-37a9-48c2-85d3-6f52b55482e6">

2. runide is ok,bug install plugin is error(custom dependency class not found)

3. Why are there two very different outcomes

4. plugin code address : https://github.com/anyilanxin/anyi-git-commit-helper

### Relevant log output or stack trace

```shell
java.lang.NoClassDefFoundError: org/apache/commons/text/StringEscapeUtils
	at com.anyilanxin.plugin.githelper.model.TypeAlias.getTitle(TypeAlias.java:43)
	at com.anyilanxin.plugin.githelper.model.TypeAlias.toString(TypeAlias.java:60)
```
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/22e932ae-c569-42a6-bd14-f10ad74077c5">
<img width="1344" alt="image" src="https://github.com/user-attachments/assets/39557bf1-4366-4779-b0a6-a779acf42409">

### Steps to reproduce

1. Packaging plug-in
2. Install the packaged plug-in
3. Click the button below to run
<img width="521" alt="image" src="https://github.com/user-attachments/assets/ff9a436b-814a-4cae-9a6f-8c27fd5ac7fe">

4. error message 'java.lang.NoClassDefFoundError: org/apache/commons/text/StringEscapeUtils'

### Gradle IntelliJ Plugin version

2.0.1

### Gradle version

8.9

### Operating System

None

**Comment by hsz** [comment]
How do you package the plugin and later install it?

**Comment by zxuanhong** [comment]
@hsz 
1. gradle task : buildPlugin
2. install plugin from disk

Is there a problem with this???

**Comment by zxuanhong** [comment]
@hsz Thank you very much. I installed the wrong package. Using a distribution is fine
