### ISSUE TITLE
Can't find `performanceTesting.jar` when building against Android Studio 2024.2.1.2

### ISSUE THREAD

**Issue by pbreault** [JetBrains/intellij-platform-gradle-plugin#1738]
### What happened?

`performanceTesting.jar` is not bundled in android studio 2024.2.1.*
This causes a resolution error in `:compileKotlin`.

### Relevant log output or stack trace

```shell
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find /Users/pbreault/.gradle/caches/8.9/transforms/55d0ff1d6fc91e695986202ef9ca3343/transformed/android-studio-2024.2.1.2-mac_arm/plugins/performanceTesting/lib/performanceTesting.jar-242.20224.300.2421.12216002+167.jar (bundledModule:com.jetbrains.performancePlugin:242.20224.300.2421.12216002+167).
     Searched in the following locations:
         file:/Users/pbreault/.gradle/caches/8.9/transforms/55d0ff1d6fc91e695986202ef9ca3343/transformed/android-studio-2024.2.1.2-mac_arm/plugins/performanceTesting/lib/performanceTesting.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

## 1. `build.gradle.kts`
```kotlin
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.9.24"
    id("org.jetbrains.intellij.platform") version "2.0.1"
}

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

intellijPlatform {
    pluginConfiguration {
        name = "example"
        group = "com.example"
    }
    buildSearchableOptions.set(false)
    instrumentCode = true
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.runIde {
    jvmArgs = listOf("-Xmx4096m", "-XX:+UnlockDiagnosticVMOptions")
}

dependencies {
    intellijPlatform {
        bundledPlugin("org.jetbrains.android")
        instrumentationTools()
        androidStudio("2024.2.1.2")

    }

    testImplementation("junit:junit:4.13.2")
    testImplementation("org.mockito:mockito-core:4.7.0")
    testImplementation("com.google.truth:truth:1.4.4")
}
```

## 2. Need at least one Kotlin file to force `:compileKotlin` to run.
```kotlin
//  src/main/kotlin/com/example/main.kt
println("hello world")
```

## 3. Repro
`gradle build`

### Gradle IntelliJ Plugin version

2.0.1

### Gradle version

8.9

### Operating System

macOS

**Comment by emertozd** [comment]
I extracted that jar from IntelliJ IDEA (2024.2) and placed it in the directory that was causing the error. Until the bug is fixed, this workaround can be used.

**Comment by kadorisio-hood** [comment]
This issue is blocking development for plugins built against `2024.2.x`.

Was the `performanceTesting.jar` dependency accidentally included in the AS bundle manifest? It seems to be an Intellij based plugin.

> I extracted that jar from IntelliJ IDEA (2024.2) and placed it in the directory that was causing the error. Until the bug is fixed, this workaround can be used.

I was able to use this workaround to get a new version published, but it's unstable and continually fails during development. It's not scalable across teams.

**Comment by dennisbordet** [comment]
I took [this one](https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/performanceTesting/performance-testing/242.23339.19/performance-testing-242.23339.19.jar) from the [repository](https://www.jetbrains.com/intellij-repository/releases/)

**Comment by qbalsdon** [comment]
I wrote a terible script! It's awful!

```
FOLDER=/Users/$USER/.gradle/caches/transforms-3/0efa82f00626821fb6f42f42cc9d940c/transformed/android-studio-2024.2.1.10-mac_arm/plugins
mkdir -p $FOLDER/performanceTesting
mkdir -p $FOLDER/performanceTesting/lib
FOLDER=$FOLDER/performanceTesting/lib/

cd ${FOLDER}
curl -O https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/performanceTesting/performance-testing/242.23339.19/performance-testing-242.23339.19.jar
```

**Comment by qbalsdon** [comment]
I have tried writing an awful workaround for my deployment pipeline, but it doesn't work... Could really use some help!

```
      - name: Missing performanceTesting jar hack fix
        run: |
          echo "see https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1738"
          FOLDER=/home/runner/.gradle/caches/transforms-3/e773a64bc76e36769f59d43df2c66fa6/transformed/android-studio-2024.2.1.10-linux/plugins                 
          mkdir -p ${FOLDER}/performanceTesting
          mkdir -p ${FOLDER}/performanceTesting/lib
          FOLDER=${FOLDER}/performanceTesting/lib
          
          FILE=performance-testing-242.23339.19.jar
          URL=https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/performanceTesting/performance-testing/242.23339.19/${FILE}
          wget -O ${FOLDER}/${FILE} ${URL}
          ls -l ${FOLDER}
```

**Comment by dennisbordet** [comment]
> I have tried writing an awful workaround for my deployment pipeline, but it doesn't work... Could really use some help!
> 
> ```
>       - name: Missing performanceTesting jar hack fix
>         run: |
>           echo "see https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1738"
>           FOLDER=/home/runner/.gradle/caches/transforms-3/e773a64bc76e36769f59d43df2c66fa6/transformed/android-studio-2024.2.1.10-linux/plugins                 
>           mkdir -p ${FOLDER}/performanceTesting
>           mkdir -p ${FOLDER}/performanceTesting/lib
>           FOLDER=${FOLDER}/performanceTesting/lib
>           
>           FILE=performance-testing-242.23339.19.jar
>           URL=https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/performanceTesting/performance-testing/242.23339.19/${FILE}
>           wget -O ${FOLDER}/${FILE} ${URL}
>           ls -l ${FOLDER}
> ```

Does this workaround work on your laptop ?
You need to rename the downloaded file to "performanceTesting.jar"

**Comment by VDenis** [comment]
> I took [this one](https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/performanceTesting/performance-testing/242.23339.19/performance-testing-242.23339.19.jar) from the [repository](https://www.jetbrains.com/intellij-repository/releases/) as a workaround. I renamed it "performanceTesting.jar" and moved it in the folder mentionned in the example

I try this solution and get error after Run plugin with exception "performanceTesting.jar' contains invalid plugin descriptor"

**Comment by Alexs784** [comment]
> I try this solution and get error after Run plugin with exception
> 
> "performanceTesting.jar' contains invalid plugin descriptor". +"WARN: Cannot load performanceTesting.jar, Cannot resolve intellij.performanceTesting.remoteDriver.xml"

I had the same. If you look at the repository link posted by @dennisbordet , you will notice there are multiple versions of the `performance-Testing.jar` file. You need to download the one corresponding to your target build.
You can find the necessary build number by looking at [this table](https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html#2024) and matching your Android Studio target version.

**Comment by qbalsdon** [comment]
@dennisbordet no, lol - nothing works - that solution was an awful attempt for my github actions, and it definitely doesn't work

**Comment by hsz** [comment]
Unfortunately, the `performancePlugin` bundled module is listed in the Android Studio's `product-info.json`, and points to the file that doesn't exist.
This bundled module comes to the `org.jetbrains.android` bundled plugin as a transitive dependency.
Fortunately, it is possible to exclude such a transitive dependency with:

```kotlin
import org.jetbrains.intellij.platform.gradle.Constants.Configurations

configurations {
    named(Configurations.INTELLIJ_PLATFORM_BUNDLED_MODULES) {
        exclude(Configurations.Dependencies.BUNDLED_MODULE_GROUP, "com.jetbrains.performancePlugin")
    }
}
```

Note that this is just a workaround; the proper fix will be included in the upcoming IntelliJ Platform Gradle Plugin release.

**Comment by joshfriend** [comment]
>  it is possible to exclude such a transitive dependency

Very helpful! Here's a groovy syntax version:

```groovy
import org.jetbrains.intellij.platform.gradle.Constants
configurations.configureEach {
  if (it.name == Constants.Configurations.INTELLIJ_PLATFORM_BUNDLED_MODULES) {
    exclude group: Constants.Configurations.Dependencies.BUNDLED_MODULE_GROUP, module: "com.jetbrains.performancePlugin"
  }
}
```

**Comment by technoir42** [comment]
This is still an issue, see #1843
