### ISSUE TITLE
description in intellijPlatform.pluginConfiguration Appends to description in plugin.xml Instead of Replacing It

### ISSUE THREAD

**Issue by pwddd** [JetBrains/intellij-platform-gradle-plugin#1744]
### What happened?

when testing the use of the description field in intellijPlatform.pluginConfiguration. Instead of replacing the existing content within the <description> tag in plugin.xml, the new content is appended to the existing description. This results in the original description not being fully replaced as intended.

### Steps to reproduce

1. My build.gradle.kts:
![image](https://github.com/user-attachments/assets/e0999940-1e9e-43cf-b24c-3da2d00c24df)
2. My plugin.xml:
![image](https://github.com/user-attachments/assets/b6696840-2e66-42a0-95df-218d18ad521a)
3. My Plugin Info:
![image](https://github.com/user-attachments/assets/6286c225-2b8f-4ad6-bda2-8f899a6205b1)

### Gradle IntelliJ Plugin version

2.0.1

### Gradle version

8.10

### Operating System

Windows

**Comment by hsz** [comment]
Thank you for reporting, @pwddd!
