### ISSUE TITLE
Modification of the plugins block doesn't invalidate the sandbox task

### ISSUE THREAD

**Issue by abrooksv** [JetBrains/intellij-platform-gradle-plugin#1745]
### What happened?

Changing disabled plugins doesn't rebuild the config folder so the plugin stays enabled.

###  Side question / request:
Would it be possible to only alter the affected `disabled_plugins.txt` instead of everything so other config settings aren't lost?

### Steps to reproduce

1. Use
```
        create("runIntelliJ") {
            type = IntelliJPlatformType.IntellijIdeaCommunity
            version = providers.gradleProperty("platformVersion")
            sandboxDirectory = layout.buildDirectory.dir("idea-sandbox/runIntelliJ")
        }
```
2. Start IDE, see Git plugin is enabled.
3. Change to
```
        create("runIntelliJ") {
            type = IntelliJPlatformType.IntellijIdeaCommunity
            version = providers.gradleProperty("platformVersion")
            sandboxDirectory = layout.buildDirectory.dir("idea-sandbox/runIntelliJ")
            plugins {
                disablePlugins("Git4Idea")
            }
        }
```
4. Start IDE, see Git plugin is still enabled.
5. Delete `build/idea-sandbox/runIntelliJ/config_runInelliJ`
6. Start IDE, see Git plugin is now disabled

### Gradle IntelliJ Plugin version

2.0.1

### Gradle version

8.10

### Operating System

macOS

**Comment by hsz** [comment]
Thanks for reporting, Austin!
