### ISSUE TITLE
[2.x] Dependency expiration invalidates config cache

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/intellij-platform-gradle-plugin#1756]
### What happened?

The dependencies that this plugin downloads periodically invalidate the gradle configuration cache. This was not an issue in 1.x versions of this plugin. 

I want to configure this plugin to get reproducible builds in which the configuration cache will not invalidate at some point in the future. I want the dependency versions I specify to be absolute and to never expire.

### Relevant log output or stack trace

```shell
Calculating task graph as configuration cache cannot be reused because cached version information for com.jetbrains.intellij.platform:test-framework:{strictly [242, 242.20224.387]; prefer 242.20224.387} has expired.
```

### Steps to reproduce

This is difficult to reproduce because the issue occurs when certain gradle cache entries expire. 

### Gradle IntelliJ Plugin version

2.0.1

### Gradle version

8.8

### Operating System

macOS

**Comment by hsz** [comment]
When defining the dependency on the Test Framework, it is possible to specify explicitly the dependency version instead of relying on the _closest_ version resolution. See the `testFramework` dependency helper method signature.
