### ISSUE TITLE
Database plugin is not loaded properly

### ISSUE THREAD

**Issue by Undin** [JetBrains/intellij-platform-gradle-plugin#1791]
### What happened?

When I add Database plugin (`com.intellij.database`) as a dependency, I expect that intellij-platform plugin will load all necessary required dependencies automatically in test to load the plugin.
But in case of database plugin, it doesn't work out of the box. I have to manually add dependency on `intellij.charts` plugin to make it work.
May it somehow relate to several `dependencies` blocks in `plugin.xml` of database plugin?

### Steps to reproduce

- checkout https://github.com/Undin/intellij-platform-gradle-plugins-bugs/commit/f5e899546ecbe1958741033b295d64d2680f0ac4 commit
- run `org.jetbrains.intellij.platform.example.DatabasePluginTest` test

To ensure that `intellij.charts` helps here, you may use https://github.com/Undin/intellij-platform-gradle-plugins-bugs/commit/e2e8c885d12a852e7e93bf070064c557472495f1 commit

### Gradle IntelliJ Plugin version

2.1.0

### Gradle version

8.7

### Operating System

macOS

**Comment by AlexanderBartash** [comment]
That is how it should already work I believe. Are you sure that the database plugin depends on `intellij.charts`? I can not find it, which jar & file are you looking at?

**Comment by Undin** [comment]
> That is how it should already work I believe. Are you sure that the database plugin depends on intellij.charts? I can not find it, which jar & file are you looking at?

Probably you cannot find it because `intellij.charts` is a transitive dependency. `com.intellij.database` has dependency on `intellij.grid.impl`, and `intellij.grid.impl` has dependency on `intellij.charts`

**Comment by AlexanderBartash** [comment]
This is a bug in the recursion:
![image](https://github.com/user-attachments/assets/df3ea4e5-4494-48fe-baa7-b40f900c415a)

**Comment by Undin** [comment]
@AlexanderBartash Yep, I also found it.
And it seems I even have a rather simple fix for it

**Comment by AlexanderBartash** [comment]
@Undin Just FYI master is broken right now.

**Comment by AlexanderBartash** [comment]
@Undin If you want you can try to build your own version with this fix from my PR or use this branch https://github.com/AlexanderBartash/intellij-platform-gradle-plugin/commit/77630c00c662484c986e57ca2d25164e22fbed9d but in this one I have so many changes, that I do it at your own risk. You can see the history yourself.

If you are going to do it, I recommend to change the version in gradle.properties & changelog to something crazy like `100500.100500.100500` then run publishToMavenLocal task. After that in your plugin project add maven local to gradle repos and you can depend on it. It is just more convenient that using an included build, if used long term.

**Comment by AlexanderBartash** [comment]
![image](https://github.com/user-attachments/assets/529554db-5321-4c1a-acbb-f6cf796a0680)

**Comment by AlexanderBartash** [comment]
That new log "An attempt to rewrite an already created Ivy module" is pretty noisy, did not expect that. I will make it info.

**Comment by hsz** [comment]
The `intellij.charts` bundled module is now correctly available by default:
<img width="1099" alt="image" src="https://github.com/user-attachments/assets/a18e5ab6-b214-4807-a138-73defd64ecd0">
