### ISSUE TITLE
Rider test-framework is missing on build

### ISSUE THREAD

**Issue by jezzsantos** [JetBrains/intellij-platform-gradle-plugin#1793]
### What happened?

Since upgrading from 1.16.1 to 2.1.0, and upgrading to `2024.1` of Rider, I am unable to compile and run my tests.
![image](https://github.com/user-attachments/assets/ab3cb9ea-60dd-46b8-9323-d10d85130fc5)

I am unable to  `import com.jetbrains.rider.test.base.BaseTestWithSolution;` and use the `BaseTestWithSolution` type.

I know a bunch has changed with this new version, becuase this type used to exist in the  `testFramework,jar` in `com.jetbrains:riderRD:2023.3`
![image](https://github.com/user-attachments/assets/cffef0e0-50f2-405b-83b7-752c5c0cfa87)

That jar file is no longer loaded by gradle for some reason.
I have done what I see mentioned in the docs to my gradle file, but I have had no luck importing that type.

Here is the top of my `build.gradle` (groovy) file:

```
import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.jetbrains.changelog.Changelog
import org.jetbrains.intellij.platform.gradle.TestFrameworkType

import java.text.SimpleDateFormat

plugins {
    id 'java'
    id 'org.jetbrains.intellij.platform' version "${intellijPluginVersion}"
    id 'org.jetbrains.changelog' version '2.0.0'
    id 'me.filippov.gradle.jvm.wrapper' version '0.14.0'
}

apply plugin: 'org.jetbrains.changelog'

group "${thisPluginGroup}"
version "${thisPluginVersion}"

java {
    sourceCompatibility = JavaVersion.VERSION_17
}

repositories {
    maven { setUrl("https://cache-redirector.jetbrains.com/maven-central") }

    intellijPlatform {
        defaultRepositories()
        jetbrainsRuntime()
    }
}

dependencies {
    implementation 'com.google.code.gson:gson:2.10'
    implementation 'com.microsoft.azure:applicationinsights-core:2.6.4'

    intellijPlatform {
        jetbrainsRuntime()
        def version = providers.gradleProperty("platformVersion").get()
        rider(version)
        instrumentationTools()

        testFramework TestFrameworkType.Bundled.INSTANCE
    }

    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.0'
    testImplementation 'org.mockito:mockito-core:4.8.0'
    testImplementation 'org.testng:testng:7.7.0'
    testRuntimeOnly 'org.junit.support:testng-engine:1.0.4'
}
```

### Steps to reproduce

Rider plugin
Upgrade intellijplugin from 1.16.1 to 2.1.0
Upgrade Gradle from 8.5 to 8.10.2
Upgrade platformVersion from 2023.3 to 2024.1

### Gradle IntelliJ Plugin version

2.1.0

### Gradle version

8.10.2

### Operating System

Windows

**Comment by AlexanderBartash** [comment]
Does the jar exist? Related code can be found here:

https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/a4e556c9e1162466f8c0fa7d042462661b835f49/src/main/kotlin/org/jetbrains/intellij/platform/gradle/extensions/IntelliJPlatformDependenciesHelper.kt#L502

**Comment by jezzsantos** [comment]
Thx @AlexanderBartash 
Sorry, it's not obvious to me where to look. Can you direct me? (I am on Windows)

**Comment by AlexanderBartash** [comment]
@jezzsantos See https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-types.html#TestFrameworkType

```
Using Bundled
The Bundled type should not be used unless it is necessary, like in the case of [Rider](https://plugins.jetbrains.com/docs/intellij/rider.html), as its test-framework is not published as an artifact.
```

Btw, not sure if you saw this https://github.com/JetBrains/intellij-platform-plugin-template may be useful.

**Comment by AlexanderBartash** [comment]
I guess this plugin still could log a warning or something, would save you time.

**Comment by jezzsantos** [comment]
Thanks @AlexanderBartash 
Sorry, none of what you have given here has helped. 
I believe I should be using `testFramework TestFrameworkType.Bundled.INSTANCE` since this is a Rider plugin, unless I am mistaken.?

Do you think I have structured the `test` task properly for version 2.10. of the plugin? here in: https://github.com/jezzsantos/automate.plugin-rider/blob/main/build.gradle

**Comment by AlexanderBartash** [comment]
@jezzsantos According to this documentation https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1793#issuecomment-2409476513 the missing jar is expected behavior. I have never tried to create any plugins for Rider, but if that is so, most likely you should try to use `testFramework(TestFrameworkType.Platform)` or other option.

**Comment by hsz** [comment]
Use `testFramework(TestFrameworkType.Bundled))`

**Comment by hsz** [comment]
It turned out that Rider doesn't distribute the `testFramework.jar` with the Rider installers. Investigating.

**Comment by AlexanderBartash** [comment]
The fix https://github.com/jezzsantos/automate.plugin-rider/pull/53/files
