### ISSUE TITLE
Bump Okio version for Retrofit

### ISSUE THREAD

**Issue by Omico** [JetBrains/intellij-platform-gradle-plugin#1795]
### What happened?

https://github.com/advisories/GHSA-w33c-445m-f8w7
https://scans.gradle.com/s/ilzsgfcvilbxw/dependencies?dependencies=okio&expandAll&focusedDependency=WzIsMSwzMCxbMCwwLFswXV1d&focusedDependencyView=versions
![image](https://github.com/user-attachments/assets/b0a5d675-51c8-401c-8b0a-149e488781e9)

### Steps to reproduce

N/A

### Gradle IntelliJ Plugin version

2.1.0

### Gradle version

8.10.2

### Operating System

None

**Comment by hsz** [comment]
Thanks for reporting!
