### ISSUE TITLE
Could not find com.jetbrains.plugins:com.intellij.java:. when calling plugins()

### ISSUE THREAD

**Issue by jwren** [JetBrains/intellij-platform-gradle-plugin#1810]
### What happened?

I am trying to upgrade an IJ plugin to `2.x`.  I have tried a number of things including different Gradle plugin versions, `2.0.0`, `2.1.0`, `2.1.1-SNAPSHOT`, using the exact code provided in this documentation, https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-migration.html#intellijplugins, as well as nesting a Gradle directory into another one, closer to where the Java code is, as well as calling different permutations of the `plugins()` method, that is `plugins(listOf("com.intellij.java"))` yields the same result for me.

Is there an example `2.x` project that I could get running locally to help migrate my plugin?

### Relevant log output or stack trace

```shell
Could not find com.jetbrains.plugins:com.intellij.java:.
     Required by:



(The same can be said for any of the output from `./third_party/gradlew printBundledPlugins`)
```

### Steps to reproduce

See what happend above.  Following directions here: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-migration.html for the Flutter IJ plugin.

### Gradle IntelliJ Plugin version

2.0.0

### Gradle version

8.2.1

### Operating System

macOS

**Comment by hsz** [comment]
The `com.intellij.java` plugin is a bundled plugin. Instead of using `plugins()` dependency helper, you should use `bundledPlugins()`

**Comment by jwren** [comment]
That was it, thank you.
