### ISSUE TITLE
PluginVerifier doesn't honor gradle offline mode

### ISSUE THREAD

**Issue by albertvaka** [JetBrains/intellij-platform-gradle-plugin#1820]
### What happened?

`ProductReleasesValueSource` tries to download the list of IDEs, even if `--offline` is passed to gradle. This makes it impossible to run the `pluginVerification` step without internet connection.

### Relevant log output or stack trace

```shell
1 problem was found storing the configuration cache.
- Build file 'build.gradle.kts': failed to compute value with custom source 'org.jetbrains.intellij.platform.gradle.providers.ProductReleasesValueSource' with java.net.UnknownHostException: www.jetbrains.com
```

### Steps to reproduce

```
pluginVerification {
        ides.select {
        }
}
```

Run `gradle` without internet connection. Even if `--offline` is passed, it still fails.

### Gradle IntelliJ Plugin version

2.1.0

**Comment by hsz** [comment]
Thanks for reporting. The fix will be available in the upcoming 2.2.0 release.
