### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by ignatov** [JetBrains/intellij-platform-gradle-plugin#1829]
### What happened?

Fetch IntelliJ SDK, switch wifi off and try to build a plugin or run tests. It's impossible right now and will be cool to have such support. BTW, it's a regression comparing to 1.xxx.

### Steps to reproduce

Turn wifi off

### Gradle IntelliJ Plugin version

2

### Gradle version

8

### Operating System

macOS

**Comment by hsz** [comment]
Can you please provide more details on what exactly is failing when in offline mode?
Is this related to #1820?

**Comment by ignatov** [comment]
yay! thanks a lot!

**Comment by ignatov** [comment]
gradle is trying to fetch files from cache redirector and failed
I suppose gradle shouldn't do that

**Comment by hsz** [comment]
Is that the current state after upgrading to 2.2.0?

**Comment by ignatov** [comment]
Build file '/Users/ignatov/src/mcp-server-plugin/build.gradle.kts' line: 10

An exception occurred applying plugin request [id: 'org.jetbrains.intellij.platform', version: '2.2.0']
> Failed to apply plugin class 'org.jetbrains.intellij.platform.gradle.plugins.project.IntelliJPlatformBasePlugin'.
   > Could not get resource 'https://www.jetbrains.com/updates/updates.xml'.
      > Could not HEAD 'https://www.jetbrains.com/updates/updates.xml'.
         > www.jetbrains.com

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 579ms
Configuration cache entry stored.

**Comment by Purus** [comment]
@hsz  @ignatov I updated the version to 2.2.1 and facing exactly the same issue as above. 

How to disable this updates.xml check?  We are behind a corporate proxy and I don't want this check to be done. 

Unable to run n gradle offline mode too as there is no cache.

**Comment by ignatov** [comment]
I worked that around with --offline flag, e.g. `./gradlew runIde --offline`

**Comment by Purus** [comment]
Didn't work for me as no cache was available to work offline..
