### ISSUE TITLE
Support LSP Test Framework

### ISSUE THREAD

**Issue by alexander-doroshko** [JetBrains/intellij-platform-gradle-plugin#1835]
### Describe the need of your request

Enable plugin developers to write tests for their LSP API-based plugins

### Proposed solution

LSP test framework is published as a Maven artifact since 2024.3.2, the plugin project could use it. As of now, it's a single file: `LspTestUtil.kt`

**Comment by hsz** [comment]
Introduced with https://github.com/JetBrains/intellij-platform-gradle-plugin/commit/2ff094cdc3cea267d6b05b19e1935f646a6cfed2
