### ISSUE TITLE
Cross build support

### ISSUE THREAD

**Issue by izhangzhihao** [JetBrains/intellij-platform-gradle-plugin#268]
Imagine the following scenario:
1. Feature one in my plugin is available for IC distributions
2. Feature two in my plugin is available for IU distributions but not for IC distributions
3. I want test the feature two with IU distributions but publish releases with IC distributions, so that if users are using IC distributions only feature one available, but if users are using IU distributions, both of the features are available.

That means, gradle-intellij-plugin will add IU distributions as dependencies as test provided, but add IC distributions as dependencies as compile provided.

**Comment by zolotov** [comment]
Thanks for the scenario

**Comment by hsz** [comment]
Running tests using different IntelliJ Platform is now possible with the 2.0 release. See: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-tasks.html#testIde
