### ISSUE TITLE
Allow running tests with all other bundled plugins loaded

### ISSUE THREAD

**Issue by auduchinok** [JetBrains/intellij-platform-gradle-plugin#336]
We've got a conflict between two plugins and it wasn't discovered in tests due to the other plugin wasn't loaded (more info: [RIDER-21655](https://youtrack.jetbrains.com/issue/RIDER-21655)). Loading all bundled plugins in tests could prevent this.

**Comment by breandan** [comment]
Somewhat related, it would be helpful to support a separate configuration for `testPlugins`, so that we can integration test interoperability between plugins which are not bundled, but should work together smoothly, cf. acejump/acejump#380.

**Comment by hsz** [comment]
Since IntelliJ Platform Gradle Plugin `2.0.0`, it's possible to define custom test tasks and disable bundled plugins:

```
val customRunIde by intellijPlatformTesting.runIde.registering {
    type = IntelliJPlatformType.Rider
    version = "2024.2"

    plugins {
        plugin("pluginId:version")
        plugin(pluginId, version, channel)
        disablePlugins(bundledPlugiId)
    }
}

val customTest by intellijPlatformTesting.testIde.registering {
    ...
}
```
