### ISSUE TITLE
Support for running other IDEs via the Running DSL

### ISSUE THREAD

**Issue by breandan** [JetBrains/intellij-platform-gradle-plugin#360]
As requested [here](https://github.com/JetBrains/gradle-intellij-plugin/issues/41#issuecomment-457570809), it would be nice if it were possible to run other IDEs configured in the [Setup DSL](https://github.com/JetBrains/gradle-intellij-plugin#setup-dsl) via the [Running DSL](https://github.com/JetBrains/gradle-intellij-plugin#running-dsl).

**Comment by breandan** [comment]
I guess this works now? I am on `0.4.5` and `:runIde` task now starts CLion as expected. Does it work for other IDEs?

**Comment by zolotov** [comment]
I don't think so. You still have to change `intellij.version` to run CLion or IDEA. Other IDEs are not support at all.

**Comment by breandan** [comment]
Right, as long as the property is set it launches CL or IU. Still, It’s a nice improvement.

**Comment by hsz** [comment]
This is now possible with IntelliJ Platform Gradle Plugin 2.0:

```kotlin
import org.jetbrains.intellij.platform.gradle.IntelliJPlatformType
import org.jetbrains.intellij.platform.gradle.tasks.RunIdeTask

tasks {
  val runPhpStorm by registering(RunIdeTask::class) {
    type = IntelliJPlatformType.PhpStorm
    version = "2023.2.2"
  }

  val runLocalIde by registering(RunIdeTask::class) {
    localPath = file("/Users/hsz/Applications/Android Studio.app")
  }
}
```

See: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-tasks.html#runIde
