### ISSUE TITLE
Take testFramework artifacts directly from Maven repository

### ISSUE THREAD

**Issue by chashnikov** [JetBrains/intellij-platform-gradle-plugin#477]
Currently gradle-intellij-plugin adds testFramework*.jar artifacts from the IDE distribution to the dependencies. However these JARs are available as separate artifact in IntelliJ artifacts repository for some time already. So we [plan](https://youtrack.jetbrains.com/issue/IDEA-238021) to remove them to reduce size of the distribution. In order to provide smooth migration for the plugin developers, it makes sense to automatically include com.jetbrains.intellij.platform:test-framework to testCompile dependencies.

**Comment by tamj0rd2** [comment]
`com.jetbrains.intellij.go` doesn't seem to be a directory under https://cache-redirector.jetbrains.com/intellij-dependencies

**Comment by artspb** [comment]
@tamj0rd2 What are you trying to achieve?

**Comment by gharrma** [comment]
Related issue: although `lib/testFramework.jar` is correctly excluded from the production runtime classpath after https://github.com/JetBrains/gradle-intellij-plugin/commit/a10955810, it still exists on the compile classpath. This makes it easy to get `NoClassDefFoundError` at runtime. You can reproduce this by referencing `com.intellij.testFramework.PlatformTestUtil` from some production sources in a plugin.

Let me know if you'd like a separate issue filed for this.

**Comment by chashnikov** [comment]
> Let me know if you'd like a separate issue filed for this.

@gharrma I think it's better to create a separate issue about that.

**Comment by hsz** [comment]
With the IntelliJ Platform Gradle Plugin 2.0, the `testFramework.jar` bundled with IDEs is no longer attached to the project — it may be even removed from the distribution in the future.
A new approach is introduced, which requires specifying an explicit dependency on the Test Framework in the project dependencies, like:

```kotlin
repositories {
  mavenCentral()

  intellijPlatform {
    defaultRepositories()
  }
}

dependencies {
  intellijPlatform {
    intellijIdeaCommunity("...")

    testFramework(TestFrameworkType.JUnit4)
  }

  // other dependencies, e.g., 3rd-party libraries
}
```

The `testFramework` helper method is a shorthand for adding Test Framework to the project (JUnit4 or JUnit5 platform variants), but also plugin/technology-specific variants, like Java, Maven, ReSharper, etc.


See [Dependencies Extension﻿](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-dependencies-extension.html) and [`TestFrameworkType﻿` type](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-types.html#TestFrameworkType) for more details.

**Comment by hurricup** [comment]
please don't remove the framework from the distro (or make up to date framework available for every build of IDE). In cases when IDE does something incompatible - testing may be troublesome.

**Comment by chashnikov** [comment]
> or make up to date framework available for every build of IDE

It should be. If you have a case where testFramework modules aren't published, please file an issue about that.
