### ISSUE TITLE
How to provide a JDK for plugin that uses `javax.tools.ToolProvider.getSystemJavaCompiler()`?

### ISSUE THREAD

**Issue by JakkuSakura** [JetBrains/intellij-platform-gradle-plugin#755]
I'm building a plugin that integrates automated program-repair into idea. However, it requires JDK 1.8, not only JRE 1.8. Is there a way to specify which runtime to use by path?

In theory, I could boot another JVM, but it is overly compilicated and can only be used as last resolve.

**Comment by hsz** [comment]
Currently, IDE requires Java 11 for runtime as well as development. Java 8 is no longer supported in both cases.

**Comment by qiujiangkun** [comment]
I can develop plugins for idea 2020.2.4, where java 8 is still supported. Now the problem is JDK
